= 업무관련

f/u:: follow up

w/:: with

w/o:: without

tl;dr:: "too long; didn't read"(너무 길어서 읽지 않았다)는 응답이 되는 어떠한 텍스트가 그 길이 때문에 무시되고 있다는 것을 말하는 인터넷 속어이다. 속어로 "Too lazy; didn't read"(너무 게을러서 읽지 않았다)를 가리킬 수도 있다. 온라인 게시물이나 신문 기사의 요약을 위한 기표로도 사용된다.

WIP:: Work in Progress

FYI:: For Your Information

24/365, 24/7/365:: 24시간 7일 365일 전체를 의미

M/M:: Man Month, 엄밀히 말하면 men per month

NCND:: neither confirm nor deny, 어떠한 시인도 부인도 하지 않음

P&L:: Profit and loss, 손익

POD:: 개념 증명(槪念證明, POC, Proof of Concept)

ROI:: Return on Investment, 투자수익률. 금융용어지만 리소스(시간, 비용, 개발) 투자 대비 돌아오는 결과를 나타낼 때에도 사용하는 것 같다. (e.g. "ROI 나오는거야?")

etc.:: ‘기타 등등’이라는 뜻의 etc.는 라틴어 et cetera의 축약형입니다.

vs.:: ‘against’를 뜻하는 vs.는 라틴어 versus의 축약형입니다.

用:: 쓸 용.

社:: 모일 사.

向:: 향할 향.

== Mail

cf.:: ‘참고’라는 뜻의 cf.는 라틴어 confer의 축약형입니다.

i.e.:: ‘다시 말하면’이라는 뜻의 i.e.는 라틴어 id est의 축약형입니다.

e.g.:: ‘예를 들면’이라는 뜻의 e.g.은 라틴어 exempli gratia의 축약형입니다.

BTW:: by the way

ASAP:: as soon as possible

FYI:: for your infomation

== GitHub

IMO(IMHO):: “In My (Humble) Opinion” 개인적인 의견 입니다만, 내 소견이지만. (humble 이 들어가면 조금 겸손한 느낌)

LGTM:: looks good to me

== 기타

e.g.:: 라틴어 exempli gratia의 약자로 영어에서는 “for example” 이나 “for the sake of example” 란 의미로 우리 말로는 “예를 들면” 의미

i.e.:: 라틴어 id est의 약자로 영어에서는 “that is to say” 이나 “in other words”에 해당되는데 즉 “다시 말해서” 의 의미

> 학술논문에서 e.g. 와 i.e. 를 사용할 때에 꼭 주의해야 할 몇 가지가 있습니다. 일단 둘 다 꼭 소문자로 사용합니다. 즉 E.G. 나 I.E는 격식에 부합되지 않는 걸로 알아두십시오. 영어 약자로 문장을 시작하지 말아주세요. 보시다시피 e.g. 와 i.e. 자모와 자모 지간에 있는 마침표를 꼭 찍어주어야 합니다. 두 번째 마침표 뒤에 쉼표를 찍어줍니다. 하지만 이는 영국식 영어에서는 조금 다를 수 있습니다. 구체적인 격식 스타일에 대한 요구가 없는 한 일반적으로 이틸랙체로 쓰지 말아야 합니다. 문장을 예로 들었을 겨우 해당 문장에 괄호를 쳐줍니다. 시카고대학 양식을 위주로 따라 하고 동시에 항상 구체적인 지침 및 스타일 가이드를 확인하고 참조해야 합니다.


---

**5W2H**

Who (누가)What (무엇을)When (언제)Where (어디서)Why (왜)How (어떻게)How much (비용은)

[source]
----
@startuml
left to right direction

(Why) --> (What)
(What) --> (When)
(What) --> (Where)
(What) --> (How)
(What) --> (How Much)

@enduml
----
