site:
  title: TIL
  start_page: blog::index.adoc

content:
  sources:
    - url: ..
      branches: HEAD
      start_path: .blog/docs
      edit_url: false

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./build/site

urls:
  latest_version_segment: ''
