= Gitflow
:toc: left
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


== Gitflow

* 이름 때문에 표준(?) 느낌이 있지만, Git을 활용한 워크플로중 하나의 아이디어일 뿐이다.
* 기본적으로 두 개의 브랜치에서 작업이 이뤄진다. `main`, `develop`
** 즉, 두 개의 브랜치에서 해당 프로젝트의 작업 이력을 관리/기록한다.
* `main` 브랜치는 공식적인 릴리즈 이력을 저장한다.
** 보통 `main` 브랜치내 커밋에 버전 번호로 https://git-scm.com/book/ko/v2/Git%EC%9D%98-%EA%B8%B0%EC%B4%88-%ED%83%9C%EA%B7%B8[태그]를 지정하여 버전 관리를 한다.
* 첫 `develop` 브랜치는 `main` 브랜치에서 만들어진다.
+
[source, bash]
----
git branch develop
git push -u origin develop
----
* `develop` 브랜치는 프로젝트의 전체 이력이 포함되는 반면, `main` 브랜치에는 요약된 버전이 포함된다.
* 모든 개발자들은 centeral(remote) repository를 등록하고, `develop` 브랜치의 추적 브랜치(https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches[tracking branch])를 만들어야 한다.

== Feature branches

* 새로운 기능 개발이 필요할 경우 백업/협업을 위해 별도 브랜치가 있어야 한다.
* 기능 개발을 위한 별도 브랜치(`feature` 브랜치)는 최신 `develop` 브랜치에서 생성한다. ( `main` 브랜치 X)
+
[source, bash]
----
git checkout develop
git checkout -b feature/add-user-service # before git 2.23
git switch -c feature/add-user-service # after git 2.23
----   
* 기능 개발이 완료되면 `develop` 브랜치로 다시 https://git-scm.com/book/ko/v2/Git-%EB%B8%8C%EB%9E%9C%EC%B9%98-%EB%B8%8C%EB%9E%9C%EC%B9%98%EC%99%80-Merge-%EC%9D%98-%EA%B8%B0%EC%B4%88[merge] 한다. `feature` 브랜치는 `main` 브랜치와 직접적인 상호작용해서는 안된다.
+
[NOTE]
====
병합(merge) 되는 방법은 다양하다. 혼자서 개발하는 프로젝트라면 로컬에서 https://git-scm.com/book/ko/v2/Git-%EB%B8%8C%EB%9E%9C%EC%B9%98-%EB%B8%8C%EB%9E%9C%EC%B9%98%EC%99%80-Merge-%EC%9D%98-%EA%B8%B0%EC%B4%88[git merge] 명령어를 통해 병합할 수도 있다.
많은 개발자들간에 협업 혹은 코드리뷰나 CI 결과를 통해 병합을 제어한다면 GitHub의 https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests[Pull Request]를 활용할 수 있다.
====

== Release branches

* 릴리즈 날짜가 다가오거나 릴리즈를 위한 기능이 충족되면 `develop` 브랜치에서 `release` 브랜치를 분기한다. (`main` 브랜치 X)
+
[source, bash]
----
git checkout develop
git switch -c release/v0.1.0
----
+
[NOTE]
.릴리즈 조건
====
위에 적혀있듯이 “릴리즈 날짜가 다가오거나 릴리즈를 위한 기능이 충족되면”이 릴리즈 브랜치가 생성되는 조건이다. develop은 언제든 prodction에 배포되는 브랜치가 아니며, 릴리즈가 준비되면 함께 해당 릴리즈 버전에 배포되어야 할 작업이 머지되어야 한다. 

main 브랜치만 관리하고, 이 브랜치가 어느 때든 배포가 가능한 브랜치 전략은 [GitHub flow](https://docs.github.com/en/get-started/quickstart/github-flow)를 참고하길 바란다.
====
* `release` 브랜치가 생성되면 다음 릴리즈 주기가 시작된다.
** `release` 브랜치는 버그 수정, 문서 생성, 해당 릴리즈에 포커싱된 작업만이 포함된다.
** `develop` 브랜치를 다음 릴리즈를 준비할 수 있으며, 이 시기부터 다음 릴리즈를 위한 `feature` 브랜치를 병합할 수 있다.
* 해당 릴리즈가 출시될 준비가 되면 `release` 브랜치를 `main` 브랜치에 병합하고, 버전 번호로 태그를 생성한다.
+
[source, bash]
----
git switch main
git merge release/v0.1.0
git tag v0.1.0
git push origin v0.1.0
----
** 또한, 릴리즈가 시작된 이후에 추가되었을 수 있는 작업들을 위해 `develop` 브랜치에도 병합(back merge)한다.
+
[source, bash]
----
git switch develop
git merge release/v0.1.0
----    
** 두 브랜치에 병합이 완료된 `release` 브랜치를 제거한다.
+
[source, bash]
----
git branch -D release/v0.1.0
----

== Hotfix branches

* `hotfix` 브랜치는 유지보수 및 긴급 대응을 위해 프로덕션 릴리즈를 빠르게 패치하기 위해 사용된다.
** 버그 수정을 위한 전담 브랜치가 있으면 나머지 워크플로를 중단하거나 릴리즈 주기에 영향을 주지 않고도 문제를 해결할 수 있다.
* `hotfix` 브랜치는 `main` 브랜치를 기반으로 생성되는 것을 제외하고는 `release` 브랜치와 유사하다.
** `main` 브랜치에서 분기되는 유일한 브랜치다.
+
[source, bash]
----
git switch main
git switch -c hotfix/bugfix-branch
----
* 기능 수정이 완료되는 즉시 `main`, `develop` 브랜치에 병합되어야 한다. 이 후, `main` 브랜치에서 업데이트된 버전으로 태그를 생성해야 한다.
+
[source, bash]
----
git switch main
git merge hotfix/bugfix-branch
git tab v0.1.1
git push origin v0.1.1
git switch develop
git merge hotfix/bugfix-branch
git branch -D hotfix/bugfix-branch
----
+
[WARNING]
.(예외) RB가 존재할 경우 어디에 back merge를 할까?
====
RB가 이미 있을 경우 `hotfix` 는 `develop` 브랜치가 아닌 RB에 merge한다. (https://community.atlassian.com/t5/Sourcetree-questions/Gitflow-hotfix-backmerge-into-release-when-release-exists/qaq-p/711966#M20073[참고])

RB가 병합될 때 develop 브랜치에도 함께 반영되고, bugfix 된 RB를 배포시에도 포함할 수 있기 때문이다.

커밋 로그가 복잡하지 않다면 hotfix 백머지된 이후에 다시 RB를 다시 생성하고 cherry-pick 하는 것도 방안일 수 있다.
====

== Support branches

* `support` 브랜치는 GItFlow에서 다루는 개념은 아니지만, 특정 시기동안에 병렬로 다양한 버전을 관리하려면 필수이다.
* major 버전업이 된 이후에 이전 버전의 hotfix를 지원해야할 때 사용할 수 있다.
* ref: https://stackoverflow.com/questions/37889187/what-is-support-command-in-git-flow

== References

* https://nvie.com/posts/a-successful-git-branching-model/[A successful Git branching model] - Vincent Driessen’s Blog
* https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow[Gitflow Rowkflow] - Atlassian
* https://cloud.google.com/architecture/devops/devops-tech-trunk-based-development?hl=ko[trunk-based development]
