= 캘린더 서비스를 위한 정리
:toc:
:left_sb: &#91;
:rigth_sb: &#93;

Calendar:: 달력, 일정표; 일정 기록.

Schedule:: (작업) 일정. https://ko.dict.naver.com/#/entry/koko/145ccd8fc80e4c47aa84caf42518b131[일정한 기간 동안 해야 할 일의 계획을 날짜별로 짜 놓은 것. 또는 그 계획.]

Event:: 사건, 일(happening, occurrence)

Task:: 할 일

Reminder:: https://en.dict.naver.com/#/entry/enko/112622646af24c9492b87ac934939a79[(이미 잊었거나 잊고 싶은 것을) 상기시키는{left_sb}생각나게 하는{rigth_sb} 것]


[plantuml]
----
@startuml
allow_mixing

agent Calendar
agent Schedule
agent Event

Calendar ||--o{ Event
Schedule ||--o{ Event

agent Task
agent Reminder

Event <|-- Task
Event <|-- Reminder

@enduml
----

== Protocols

=== CalDAV
:caldav: https://en.wikipedia.org/wiki/CalDAV
:webdav: https://en.wikipedia.org/wiki/WebDAV
:ical: https://en.wikipedia.org/wiki/ICalendar#Free/busy_time_(VFREEBUSY)
:rfc4791: https://www.rfc-editor.org/rfc/rfc4791
:rfc6638: https://datatracker.ietf.org/doc/html/rfc6638

* {caldav}[CalDAV]은 Calendaring Extensions to WebDAV의 약자로 캘린더의 정보를 서버와 동기화하기 위한 공개 프로토콜
* {webdav}[WebDAV]의 확장
+
WebDAV:: WebDAV는 Web-based Distributed Authoring and Versioning(웹기반 분산형 저작 및 버전관리)의 약어입니다. 이는 HTTP(S) 프로토콜의 확장 세트로서 이를 사용하여 웹 서버를 표준 네트워크 드라이브로 표시할 수 있습니다. 
* HTTP를 기반으로 {ical}[iCalendar] 포맷을 통해 데이터를 통신함. 프로토콜에 대한 상세 정보는 https://www.rfc-editor.org/rfc/rfc4791[RFC 4791]
* 스케줄링 관리 관련해서는 {rfc6638}[RFC 6638: Scheduling Extensions to CalDAV]

==== References

* https://calyfactory.github.io/caldav-sync-1/

=== iCalendar

* {ical}[iCalendar]^Internet{sp}Calendaring{sp}and{sp}Scheduling{sp}Core{sp}Object{sp}Specification^는 사용자가 이벤트, 할 일, 저널 항목, 약속 있음/없음 정보와 같은 일정 및 일정 정보를 저장하고 교환할 수 있는 미디어 유형입니다.


=== Webcal

* {caldav}[CalDAV]와 GroupDAV는 모두 WebDAV 기반의 캘린더 저장소 액세스를 보다 세밀하게 제공하기 위한 노력입니다.
* CalDAV 액세스 프로토콜은 IETF에 의해 표준화되었으며 {rfc4791}[RFC 4791]로 게시되었습니다. 자동 일정 관리를 위한 CalDAV 확장도 {rfc6638}[RFC 6638]로 표준화되었습니다.

=== References

* https://en.wikipedia.org/wiki/Web_Calendar_Access_Protocol[WCAP]
