= RFC 2446 - iTIP
:toc: left
:source-highlighter: highlight.js

:rfc2446: https://www.rfc-editor.org/rfc/rfc2446

[.text-center]
****
{rfc2446}[**iCalendar Transport-Independent Interoperability Protocol**] +
{rfc2446}[**(iTIP)**] +
{rfc2446}[**Scheduling Events, BusyTime, To-dos and Journal Entries**]
****

== 개요

이 문서는 캘린더 시스템이 iCalendar 객체를 사용하여 다른 캘린더 시스템과 상호 운용하는 방법을 지정합니다. 이는 시스템 간의 다양한 통신 방법을 허용하기 위해 일반적인 방식으로 수행됩니다. 후속 문서에서는 이 프로토콜을 사용하는 시스템 간의 상호 운용 가능한 통신 방법을 지정합니다.

이 문서에서는 static 및 dynamic event, to-do, journal, free/busy 개체를 모두 정의하는 캘린더 교환 모델을 간략하게 설명합니다. static 객체는 원본 항목과의 연속성이나 참조 무결성을 기대하지 않고 한 개체에서 다른 개체로 정보를 전송하는 데 사용됩니다. dyamic 객체는 정적 객체의 상위 집합이며 static 객체만 지원하는 클라이언트의 경우 static 객체로 자연스럽게 저하됩니다.

이 문서는 서로 다른 캘린더 시스템 간에 일정관리 상호 운용성을 제공하는 iCalendar 객체 사양을 기반으로 하는 인터넷 프로토콜을 지정합니다. 이 인터넷 프로토콜을 "iTIP(iCalendar 전송 독립적 상호 운용성 프로토콜)"이라고 합니다.

iTIP는 현재 캘린더 시스템에서 일반적으로 사용할 수 있는 그룹 스케줄링 메서드에 대한 시맨틱을 추가하여 iCalendar 객체 사양을 보완합니다. 이러한 예약 방법을 사용하면 두 개 이상의 캘린더 시스템이 게시, 예약, 일정 재조정, 예약 요청에 대한 응답, 변경 협상 또는 iCalendar 기반 캘린더 구성 요소 취소와 같은 트랜잭션을 수행할 수 있습니다.

iTIP는 스케줄링 정보를 전송하는 데 사용되는 특정 전송 방식과 무관하게 정의됩니다. iTIP에 대한 동반 메모는 여러 인터넷 프로토콜에 대한 상호 운용성 프로토콜의 바인딩을 제공합니다.

:sectnums:

== Introduction

이 문서는 캘린더 시스템이 iCalendar 개체를 사용하여 다른 캘린더 시스템과 상호 운용하는 방법을 지정합니다. 특히 event, to-do 또는 daily journal 항목을 예약하는 방법을 명시합니다. 또한 사용 가능한 바쁜(busy) 시간 정보를 검색하는 방법을 지정합니다. 이는 시스템 간의 다양한 통신 방법을 허용하기 위해 일반적인 방식으로 수행됩니다. 후속 문서에서는 이 프로토콜을 사용하는 시스템 간의 전송 바인딩을 지정합니다.

이 프로토콜은 발신자(originator)가 한 명 이상의 수신자(recipients)에게 보내는 메시지를 기반으로 합니다. 특정 유형의 메시지에 대해 수신자는 자신의 상태를 업데이트하기 위해 응답할 수 있으며 트랜잭션/요청 상태 정보를 반환할 수도 있습니다. 이 프로토콜은 메시지 발신자가 원래 메시지를 수정하거나 취소할 수 있는 기능을 지원합니다. 또한 프로토콜은 수신자가 메시지 발신자에게 변경 사항을 제안할 수 있는 기능도 지원합니다. 프로토콜의 요소는 트랜잭션에 대한 사용자 역할도 정의합니다.

=== Formatting Conventions

캘린더링 및 스케줄링 모델, 핵심 객체 또는 상호 운용성 프로토콜의 요소를 참조하기 위해 [iCAL] 및 [iTIP]에 정의된 몇 가지 형식 규칙이 활용되었습니다.

이 문서에서 "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENT", "MAY" 및 "OPTIONAL"이라는 키워드는 [RFC-2119]에 설명된 대로 해석되어야 합니다.

캘린더 및 스케줄링 역할은 각 단어의 첫 글자를 대문자로 따옴표로 묶은 텍스트 문자열로 참조됩니다. 예를 들어, 'Organizer'(주최자)는 [iTIP]에 정의된 스케줄링 프로토콜 내에서 'Calendar User(캘린더 사용자)'(CU)의 역할을 나타냅니다. [iCAL]에 정의된 캘린더 구성 요소는 대문자로 따옴표로 묶인 문자열로 참조됩니다. 모든 캘린더 구성 요소는 문자 "V"로 시작합니다. 예를 들어, "VEVENT"는 이벤트 캘린더 구성 요소, "VTODO"는 할 일 캘린더 구성 요소, "VJOURNAL"은 일일 저널 캘린더 구성 요소를 나타냅니다. [iTIP]에 정의된 스케줄링 메서드는 대문자로 따옴표로 묶인 텍스트로 참조됩니다. 예를 들어, "REQUEST"은 일정관리 캘린더 구성 요소의 생성 또는 수정을 요청하는 메서드를 의미하고, "REPLY"은 요청을 받은 사람이 캘린더 구성 요소의 "Organizer"에게 자신의 상태를 업데이트하는 데 사용하는 메서드를 의미합니다.

[iCAL]에 정의된 속성은 대문자로 따옴표로 묶인 텍스트 문자열 뒤에 "property"이라는 단어가 붙어서 참조됩니다. 예를 들어, "ATTENDEE"(참석자) 속성은 "Calendar User"(캘린더 사용자)의 캘린더 주소를 전달하는 데 사용되는 iCalendar 속성을 나타냅니다. 이 메모에 정의된 속성 매개변수는 소문자로 따옴표로 묶인 텍스트 문자열 뒤에 "parameter"라는 단어가 붙어서 참조됩니다. 예를 들어, "value" 매개변수는 속성 값의 기본 데이터 유형을 재정의하는 데 사용되는 iCalendar 속성 매개변수를 나타냅니다. 이 메모에 정의된 열거형 값은 대문자로 된 텍스트를 단독으로 사용하거나 그 뒤에 "value"라는 단어를 사용하여 참조합니다.

테이블에서는 테이블 길이를 최소화하기 위해 따옴표로 묶인 문자열 텍스트가 따옴표 없이 지정됩니다.

=== Related Documents

구현자는 이 문서와 함께 인터넷 캘린더 및 스케줄링 표준을 설명하는 다른 여러 메모를 숙지하고 있어야 합니다. 이 문서인 [iTIP]는 서로 다른 구현 간의 스케줄링을 위한 상호 운용성 프로토콜을 지정합니다. 관련 문서는 다음과 같습니다:

* [iCAL] - 프로토콜에 사용되는 객체, 데이터 유형, 속성 및 속성 매개변수와 이를 표현하고 인코딩하는 방법을 지정합니다;
* [iMIP] - [iTIP]에 대한 인터넷 이메일 바인딩을 지정합니다.

이 메모에서는 이러한 다른 메모의 개념이나 정의에 대한 사양을 반복하지 않습니다. 가능한 경우 이러한 개념 또는 정의의 사양을 제공하는 메모를 참조합니다.

=== ITIP Roles and Transactions

ITIP는 "Calendar User"(CU) 간의 그룹 캘린더링 및 예약을 목적으로 [iCAL] 개체를 교환하는 방법을 정의합니다. CU는 iTIP에서 두 가지 역할 중 하나를 수행합니다. 교환을 시작한 CU는 "Organizer"(주최자) 역할을 맡습니다. 예를 들어, 그룹 모임을 제안한 CU가 "Organizer"입니다. "Organizer"로부터 그룹 미팅에 참여하도록 요청받은 CU는 "Attendee"(참석자) 역할을 맡습니다. "role"은 \_ATTENDEE\_ 속성에 대한 설명 매개변수이기도 합니다. 이 매개변수는 'chair', 'req-participant' 또는 'non-participant'와 같이 'Attendee'에게 설명적인 컨텍스트를 전달하는 데 사용되며 캘린더 워크플로와는 아무런 관련이 없습니다.

ITIP 메서드는 아래에 나열되어 있으며 그 사용법과 의미는 이 문서의 섹션 3에 정의되어 있습니다.

[%autowidth]
|===
| Method | Description

| PUBLISH | 한 명 이상의 캘린더 사용자에게 캘린더 항목을 게시하는 데 사용됩니다. 게시자와 다른 캘린더 사용자 간에는 상호 작용이 없습니다. 예를 들어 야구 팀이 대중에게 일정을 게시하는 경우를 들 수 있습니다.
| REQUEST | 다른 캘린더 사용자와 캘린더 항목을 예약하는 데 사용됩니다. 요청은 수신자가 응답 메서드를 사용해 응답해야 한다는 점에서 대화형입니다. 미팅 요청, 바쁨 시간 요청, 다른 캘린더 사용자에게 VTODO 할당 등이 모두 그 예입니다. 요청은 'Organizer'가 캘린더 항목의 상태를 업데이트하는 데에도 사용됩니다.
| REPLY | Reply은 'Attendee' 상태를 'Organizer'에게 전달해 달라는 요청에 대한 응답으로 사용됩니다. 회신은 일반적으로 미팅 및 작업 요청에 응답하는 데 사용됩니다.
| ADD | 기존 VEVENT, VTODO 또는 VJOURNAL에 하나 이상의 인스턴스를 추가합니다.
| CANCEL | 기존 VEVENT, VTODO 또는 VJOURNAL의 인스턴스를 하나 이상 취소합니다.
| REFRESH | REFRESH 방법은 'Attendee'가 캘린더 항목의 최신 버전을 요청하는 데 사용됩니다.
| COUNTER | Counter 메서드는 'Attendee'가 캘린더 항목의 변경을 협상하는 데 사용됩니다. 예를 들어, 제안된 이벤트 시간을 변경하거나 VTODO의 마감일을 변경하는 요청이 있습니다.
| DECLINE-COUNTER | "Organizer"가 제안된 반대 제안을 거부하는 데 사용됩니다.
|===

iTIP에서 그룹 예약은 위에서 설명한 "request" 및 "response" 메서드 세트를 사용하여 수행됩니다. 다음 표는 메서드를 보낼 수 있는 사람에 따라 분류된 메서드를 보여줍니다.

[%autowidth]
|===
| Originator | Methods

| Organizer | PUBLISH, REQUEST, ADD, CANCEL, DECLINECOUNTER
| Attendee | REPLY, REFRESH, COUNTER   REQUEST only when delegating
|===

일부 캘린더 컴포넌트 유형의 경우 허용되는 메서드가 위 집합의 하위 집합이라는 점에 유의하세요.


나중에 찾아보기 위해 RFC 2446을 번역된 것 남김.

== Interoperability Models
상호 운용성과 관련된 프로토콜에는 "응용 프로그램 프로토콜"과 "전송 프로토콜"이라는 두 가지가 있습니다. 애플리케이션 프로토콜은 위에 나열된 스케줄링 트랜잭션을 수행하기 위해 발신자와 수신자 간에 전송되는 iCalendar 개체의 내용을 정의합니다. 전송 프로토콜은 발신자와 수신자 간에 iCalendar 개체를 전송하는 방법을 정의합니다. 이 문서는 애플리케이션 프로토콜에 중점을 둡니다. iMIP]와 같은 바인딩 문서는 전송 프로토콜에 중점을 둡니다.

아래 다이어그램에서 발신자와 수신자 간의 연결은 애플리케이션 프로토콜을 참조합니다. 발신자에서 수신자에게 전달되는 iCalendar 개체는 섹션 3, 애플리케이션 프로토콜 요소에 나와 있습니다.

[ditaa]
....
+----------+                      +----------+
|          |        iTIP          |          |
| Sender   |<-------------------->| Receiver |
|          |                      |          |
+----------+                      +----------+
....

이 다이어그램에는 발신자와 수신자가 'Calendar User Agent(CUA)' 또는 'Calendar Service(CS)'의 다양한 역할을 맡는 여러 가지 변형이 있습니다.

iTIP의 아키텍처는 아래 다이어그램에 나와 있습니다. 이 사양에 따라 작성된 애플리케이션은 저장 후 전달 전송, 실시간 전송 또는 둘 다에 대한 바인딩과 함께 작동할 수 있습니다. 또한 iTIP는 다른 전송에 바인딩될 수도 있습니다.

[ditaa]
....
+------------------------------------------+
|                   iTIP                   |
+------------------------------------------+
|Real‒time | Store‒and‒Fwd | Other         |
|Transport | Transport     | Transports... |
+------------------------------------------+
....

=== Application Protocol

iTIP 모델에서 캘린더 항목은 "주최자"가 생성하고 관리합니다. "주최자"는 위에 나열된 iTIP 메시지 중 하나 이상을 전송하여 다른 CU와 상호 작용합니다. "참석자"는 "회신" 방법을 사용하여 자신의 상태를 전달합니다. "참석자"는 마스터 캘린더 항목을 직접 변경할 수 없습니다. 그러나 "카운터" 방법을 사용하여 "주최자"에게 변경 사항을 제안할 수 있습니다. 어떤 경우든 "주최자"는 마스터 캘린더 항목을 완전히 제어할 수 있습니다.

==== Calendar Entry State

캘린더 항목과 관련된 상태에는 항목의 전체 상태와 해당 항목의 '참석자'와 관련된 상태라는 두 가지가 있습니다.

항목의 상태는 "상태" 속성에 의해 정의되며 "주최자"에 의해 제어됩니다. "상태" 속성에는 기본값이 없습니다. "주최자"는 "상태" 속성을 각 일정관리 항목에 적합한 값으로 설정합니다.

항목과 관련된 특정 "참석자"의 상태는 각 "참석자"의 "참석자" 속성에 있는 "partstat" 매개변수에 의해 정의됩니다. "주최자"가 초기 항목을 발행하면 "참석자" 상태를 알 수 없습니다. "주최자"는 "partstat" 매개변수를 "NEEDS-ACTION"으로 설정하여 이를 지정합니다. 각 "참석자"는 "참석자" 속성의 "partstat" 매개변수를 적절한 값으로 수정하여 "주최자"에게 다시 보내는 "REPLY" 메시지의 일부로 사용합니다.

==== Delegation

위임은 "참석자"가 다른 CU(또는 여러 CU)에 자신을 대신하여 참석할 수 있는 권한을 부여하는 절차로 정의됩니다. "주최자"는 위임하는 "참석자"가 "주최자"에게 알리기 때문에 이러한 변경 사항을 알게 됩니다. 이러한 단계는 요청 방법 섹션에 자세히 설명되어 있습니다.

==== Acting on Behalf of other Calendar Users

많은 조직에서 한 사용자가 다른 사용자를 대신하여 미팅 요청을 조직하거나 응답합니다. ITIP는 이러한 활동을 지원하는 두 가지 메커니즘을 제공합니다.

첫째, '주최자'는 '참석자'와는 별개의 특수한 개체로 취급됩니다. '참석자'의 모든 응답은 '주최자'에게 전달되므로 미팅을 조직하는 캘린더 사용자와 미팅에 참석하는 캘린더 사용자를 쉽게 구분할 수 있습니다. 또한, iCalendar는 각 "참석자"에 대해 설명적인 역할을 제공합니다. 예를 들어, '의장'이라는 역할은 한 명 이상의 '참석자'에게 할당될 수 있습니다. "의장"과 "주최자"는 동일한 캘린더 사용자일 수도 있고 아닐 수도 있습니다. 이는 어시스턴트가 회의의 의장을 맡은 다른 사람을 위해 회의 일정을 관리할 수 있는 시나리오에 잘 부합합니다.

둘째, '보낸 사람' 매개변수는 '주최자' 또는 '참석자' 속성 중 하나에 지정할 수 있습니다. 지정된 경우, "보낸 사람" 매개변수는 응답하는 CU가 지정된 "참석자" 또는 "주최자"를 대신하여 작업했음을 나타냅니다.

==== Component Revisions

"SEQUENCE" 속성은 "주최자"가 캘린더 구성 요소의 수정본을 표시하는 데 사용됩니다. "SEQUENCE" 숫자를 증가시키는 규칙은 [iCAL]에 정의되어 있습니다. 명확성을 위해 여기서는 이러한 규칙을 [iTIP]에서 적용되는 방식에 따라 의역했습니다. 캘린더 컴포넌트에서 주어진 "UID"에 대해:

. "PUBLISH" 및 "REQUEST" 메서드의 경우, [iCAL]에 정의된 규칙에 따라 "SEQUENCE" 속성 값이 증가합니다.
. "주최자"가 "추가" 또는 "취소" 메서드를 사용할 때마다 "SEQUENCE" 속성 값은 반드시 증가해야 합니다.
. "응답", "새로고침", "카운터", "선언 카운터"를 사용하거나 "요청" 위임을 보낼 때 "SEQUENCE" 속성 값을 증가시키면 안됩니다.

경우에 따라 "주최자"는 발송된 최종 수정본에 대한 응답을 받지 못할 수도 있습니다. 이 경우 "주최자"는 업데이트 "REQUEST"를 보내고 모든 "참석자"에 대해 "RSVP=TRUE"를 설정하여 현재 응답을 수집할 수 있도록 할 수 있습니다.

"참석자"의 응답에 포함된 "SEQUENCE" 속성 값은 "주최자"의 수정본과 항상 일치하지 않을 수 있습니다. 구현은 CUA가 CU에 응답이 수정된 항목에 대한 것임을 표시하고 CU가 응답을 수락할지 여부를 결정하도록 선택할 수 있습니다.

==== Message Sequencing

[iTIP] 애플리케이션 프로토콜을 처리하는 CUA는 종종 캘린더 저장소의 구성 요소와 [iTIP] 메시지로 수신된 구성 요소를 연관시켜야 합니다. 예를 들어, 이벤트가 동일한 이벤트의 이후 개정판으로 업데이트될 수 있습니다. 이를 위해 CUA는 캘린더 저장소에 이미 있는 이벤트의 버전과 [iTIP] 메시지로 전송된 버전을 상호 연관시켜야 합니다. 이러한 상관관계 외에도 [iTIP] 메시지가 예기치 않은 순서로 도착하는 원인이 될 수 있는 몇 가지 요인이 있습니다. 즉, '주최자'가 구성 요소의 이전 버전에 대한 회신을 받은 후에 이후 버전에 대한 회신을 받을 수 있습니다.

상호 운용성을 극대화하고 예기치 않은 순서로 도착하는 메시지를 처리하려면 다음 규칙을 사용하세요:

. 특정 iCalendar 구성 요소를 참조하기 위한 기본 키는 "UID" 속성 값입니다. 반복 구성 요소의 인스턴스를 참조하기 위해 기본 키는 "UID" 및 "RECURRENCE-ID" 속성으로 구성됩니다.
. 컴포넌트를 참조하기 위한 보조 키는 "SEQUENCE" 속성 값입니다. "UID"가 동일한 컴포넌트의 경우, "SEQUENCE" 속성 값이 가장 높은 컴포넌트가 낮은 값을 가진 컴포넌트의 다른 모든 리비전을 무시합니다.
. "참석자"는 "주최자"에게 "REPLY" 메시지를 보냅니다. "UID" 속성 값이 동일한 답장의 경우, "SEQUENCE" 속성 값은 "참석자"가 답장하는 구성 요소의 리비전을 나타냅니다. "SEQUENCE" 속성의 가장 높은 숫자 값을 가진 회신은 낮은 값을 가진 다른 모든 회신을 무시합니다.
. "UID" 및 "SEQUENCE" 속성이 일치하는 경우, "DTSTAMP" 속성이 동점자로 사용됩니다. 가장 최근의 "DTSTAMP"를 가진 구성 요소가 다른 모든 구성 요소보다 우선합니다. 마찬가지로 "UID" 속성 값이 일치하고 "SEQUENCE" 속성 값이 일치하는 "참석자" 응답의 경우 가장 최근의 "DTSTAMP"가 있는 응답이 다른 모든 응답보다 우선합니다.

따라서 CUA는 다음 구성 요소 속성을 유지해야 합니다: "UID", "RECURRENCE-ID", "SEQUENCE" 및 "DTSTAMP". 또한 구성 요소의 각 "참석자" 속성에 대해 CUA는 "참석자"의 응답과 관련된 "SEQUENCE" 및 "DTSTAMP" 속성 값을 유지해야 합니다.

== Application Protocol Elements
