= Internet Calendaring and Scheduling Core Object Specification (iCalendar)
:toc: left
:rfc5545: https://datatracker.ietf.org/doc/html/rfc5545

****
{rfc5545}[RFC 5545]는 캘린더 서비스나 프로토콜에 관계 없이 events, to-dos, journal entries, free/busy information와 같은 캘린더 및 일정 정보를 표현하고 교환하기 위한 iCalendar 데이터 포맷을 정의한다.
****

== Introduction

변화하는 인터넷 환경에서 사용할 수 있는 캘린더와 스케줄 데이이터를 교환하기 위해 Internet Calendaring and Scheduling Core Object Specification(이하 iCalendar)라 불리는 MIME 컨텐트 타입을 정의한다.

또한, iCalendar 오브젝트인 회의나 설비(appointments), 할 일, 저널에 대한 요청, 응답, 수정 및 취소 메서드들과 바쁨 일정의 요청/응답과 같은 다양한 속성들을 정의한다. https://datatracker.ietf.org/doc/html/rfc5545#ref-2446bis[2446bis]에 정의된 iCalendar Transport-independent Interoperability Protocol (iTIP)에 일정 프로토콜을 정의한다.

MIME 타입:: 클라이언트에게 전송된 문서의 다양성을 알려주기 위한 메커니즘이다. 웹에서 파일의 확장자는 의미가 없으며, 클라이언트에게 어떤 형식인지를 전달하기 위해 서버가 설정하는 타입이다. (https://developer.mozilla.org/ko/docs/Web/HTTP/Basics_of_HTTP/MIME_types[참고])

== Basic Grammar and Conventions

이 문서에는 RFC5234에 정의된 Internet ABNF 기반의 컨텐트 타입 문법이 포함되어 있다.
