= RFC 5445 - iCalendar
:toc: left
:sectnums:
:source-highlighter: highlight.js

[.text-center]
****
**Internet Calendaring and Scheduling Core Object Specification** +
**(iCalendar)**
****

====
Origin: https://datatracker.ietf.org/doc/html/rfc5545[RFC 5545 - Internet Calendaring and Scheduling Core Object Specification (iCalendar)]
====

:rfc5545: https://datatracker.ietf.org/doc/html/rfc5545

****
{rfc5545}[RFC 5545]는 캘린더 서비스나 프로토콜에 관계 없이 events, to-dos, journal entries, free/busy information와 같은 캘린더 및 일정 정보를 표현하고 교환하기 위한 iCalendar 데이터 포맷을 정의한다.
****

== Introduction

지난 10년 동안 캘린더 및 일정 관리의 사용은 상당히 증가했습니다.  기업 및 기업 간 비즈니스는 이 정보 기술을 사용하여 이벤트와 작업을 신속하게 예약하는 데 의존하게 되었습니다.  이 메모는 서로 다른 캘린더 및 스케줄링 애플리케이션 간의 상호 운용성 수준을 발전시키기 위한 것입니다.  이 메모는 전자 캘린더 및 스케줄링 정보를 교환하기 위한 MIME 콘텐츠 유형을 정의합니다.  인터넷 캘린더 및 스케줄링 핵심 객체 사양(iCalendar)을 사용하면 개인 정보 관리자(PIM) 또는 그룹 스케줄링 제품과 같이 일반적으로 캘린더 및 스케줄링 애플리케이션 내에 저장된 정보를 캡처하고 교환할 수 있습니다.

iCalendar 형식은 애플리케이션 또는 시스템 간의 교환 형식으로 적합합니다.  이 형식은 MIME 콘텐츠 유형으로 정의됩니다.  따라서 SMTP, HTTP, 파일 시스템, 메모리 기반 클립보드 사용 또는 끌어서 놓기 상호 작용과 같은 데스크톱 대화형 프로토콜, 지점 간 비동기 통신, 유선 네트워크 전송 또는 적외선과 같은 일부 형태의 무선 전송을 포함하되 이에 국한되지 않는 여러 전송을 사용하여 개체를 교환할 수 있습니다.

또한 이 메모에서는 회의나 약속, 할 일, 저널 항목의 요청, 회신, 수정, 취소와 같은 캘린더 및 예약 작업을 지원하기 위해 이 콘텐츠 유형을 메시지 세트에 매핑하는 iCalendar 객체 메서드의 정의에 대해서도 설명합니다.  iCalendar 객체 메서드를 사용하여 여유 시간/바쁨 시간 데이터 요청 및 응답과 같은 기타 캘린더 및 스케줄링 작업을 정의할 수 있습니다.  이러한 스케줄링 프로토콜은 [2446bis]에 정의된 iTIP(iCalendar 전송 독립적 상호 운용성 프로토콜)에 정의되어 있습니다.

이 메모에는 [RFC5234]에 정의된 인터넷 ABNF에 기반한 콘텐츠 유형에 대한 공식 문법도 포함되어 있습니다.  이 ABNF는 파서 구현에 필요하며 메모의 설명적 산문 정의를 해석할 때 모호함이나 의문이 발생할 때 최종 참조 자료로 사용됩니다.  ABNF 구문으로 쉽게 표현할 수 없는 추가 제한 사항은 ABNF에서 주석으로 지정됩니다.  규범적인 문장이 포함된 주석은 그렇게 취급해야 합니다.

[NOTE]
====
MIME 타입:: 클라이언트에게 전송된 문서의 다양성을 알려주기 위한 메커니즘이다. 웹에서 파일의 확장자는 의미가 없으며, 클라이언트에게 어떤 형식인지를 전달하기 위해 서버가 설정하는 타입이다. (https://developer.mozilla.org/ko/docs/Web/HTTP/Basics_of_HTTP/MIME_types[참고])
====

== Basic Grammar and Conventions

이 문서에서 "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY" 및 "OPTIONAL"이라는 키워드는 [RFC2119]에 설명된 대로 해석해야 합니다.

이 메모는 캘린더 및 일정 관리 형식을 정의하기 위해 설명적인 산문과 보다 공식적인 표기법을 모두 사용합니다.

이 메모에 사용된 표기법은 [RFC5234]의 ABNF 표기법입니다. 이 메모에 정의된 형식을 구현하려는 독자는 이 표기법을 숙지해야 이 메모의 사양을 올바르게 해석할 수 있습니다.

이 메모에서 사용된 모든 숫자 값은 십진수 표기법으로 제공됩니다.

프로퍼티, 프로퍼티 매개변수, 열거된 프로퍼티 값, 프로퍼티 매개변수 값의 모든 이름은 대소문자를 구분하지 않습니다.  그러나 다른 모든 속성 값은 달리 명시되지 않는 한 대소문자를 구분합니다.

[NOTE]
====
이와 같이 들여쓰기된 모든 편집 노트는 독자에게 추가 정보를 제공하기 위한 것입니다.  이 정보는 이 메모를 준수하는 구현을 구축하는 데 필수적인 것은 아닙니다.  이 정보는 메모의 특정 기능이나 특성을 강조하기 위해 제공됩니다.
====

iCalendar 객체의 형식은 텍스트/디렉토리 미디어 유형[RFC2425]의 구문을 기반으로 합니다.  iCalendar 개체는 텍스트/디렉토리 미디어 유형 [RFC2425]의 프로파일은 아니지만, [RFC2425] 사양의 여러 요소를 재사용합니다.

=== Formatting Conventions

이 메모에 정의된 요소는 산문으로 정의되어 있습니다.  이를 설명하는 데 사용된 많은 용어는 이 메모의 표준 사용법과 다른 일반적인 사용법을 가지고 있습니다.  이 메모에서는 캘린더 및 스케줄링 모델, 핵심 객체(이 메모) 또는 상호 운용성 프로토콜[2446bis]의 요소를 참조하기 위해 몇 가지 서식 규칙을 사용했습니다.  캘린더 및 일정 관리 역할은 따옴표로 묶인 텍스트 문자열로 참조되며 각 단어의 첫 글자는 대문자로 표시됩니다.  예를 들어, '주최자'는 [2446bis]에 정의된 스케줄링 프로토콜 내에서 '캘린더 사용자'의 역할을 의미합니다.  이 메모에 정의된 캘린더 구성 요소는 대문자로 따옴표로 묶인 문자열로 참조됩니다.  모든 캘린더 구성요소는 문자 "V"로 시작합니다.  예를 들어, "VEVENT"는 이벤트 캘린더 구성요소, "VTODO"는 할 일 캘린더 구성요소, "VJOURNAL"은 일일 일기 캘린더 구성요소를 나타냅니다. iTIP [2446bis]에 정의된 스케줄링 메서드는 대문자로 따옴표로 묶인 텍스트 문자열로 참조됩니다.  예를 들어, "요청"은 일정관리 캘린더 구성 요소의 생성 또는 수정을 요청하는 메서드를 의미하며, "회신"은 요청을 받은 사람이 캘린더 구성 요소의 "주최자"에게 자신의 상태를 업데이트하는 데 사용하는 메서드를 의미합니다.

이 메모에 정의된 속성은 대문자로 따옴표로 묶인 텍스트 문자열 뒤에 "속성"이라는 단어가 붙어서 참조됩니다.  예를 들어, "참석자" 속성은 캘린더 사용자의 캘린더 주소를 전달하는 데 사용되는 iCalendar 속성을 나타냅니다.  이 메모에 정의된 속성 매개변수는 소문자로 따옴표로 묶인 텍스트 문자열 뒤에 "매개변수"라는 단어가 붙어서 참조됩니다.  예를 들어, "value" 매개변수는 속성 값의 기본값 유형을 재정의하는 데 사용되는 iCalendar 속성 매개변수를 나타냅니다.  이 메모에 정의된 열거된 값은 대문자로 된 텍스트를 단독으로 사용하거나 그 뒤에 "value"라는 단어를 사용하여 참조합니다.  예를 들어, "MINUTELY" 값은 "RECUR" 값 유형의 "FREQ" 구성 요소와 함께 사용하여 1분 이상의 간격을 기준으로 반복 구성 요소를 지정할 수 있습니다.

다음 표에는 이 문서에서 참조하는 [US-ASCII] 문자 집합의 다양한 문자가 나열되어 있습니다.  각 문자에 대해 이 표에는 이 문서 전체에서 사용되는 문자 이름과 해당 US-ASCII 소수점 코드포인트가 명시되어 있습니다.

[%autowidth]
|===
| Character name         | Decimal codepoint

| HTAB                   | 9
| LF                     | 10
| CR                     | 13
| DQUOTE                 | 22
| SPACE                  | 32
| PLUS SIGN              | 43
| COMMA                  | 44
| HYPHEN-MINUS           | 45
| PERIOD                 | 46
| SOLIDUS                | 47
| COLON                  | 58
| SEMICOLON              | 59
| LATIN CAPITAL LETTER N | 78
| LATIN CAPITAL LETTER T | 84
| LATIN CAPITAL LETTER X | 88
| LATIN CAPITAL LETTER Z | 90
| BACKSLASH              | 92
| LATIN SMALL LETTER N   | 110
|===

=== Related Memos

구현자는 이 메모와 함께 인터넷 캘린더 및 스케줄링 표준을 위한 프레임워크를 구성하는 다른 여러 메모를 숙지해야 합니다.  이 메모는 객체, 값 유형, 속성 및 속성 매개변수에 대한 핵심 사양을 지정합니다.

* iTIP [2446bis]는 서로 다른 구현 간의 스케줄링을 위한 상호 운용성 프로토콜을 지정합니다;
* iCalendar 메시지 기반 상호 운용성 프로토콜(iMIP) [2447bis]는 [2446bis]에 대한 인터넷 이메일 바인딩을 지정합니다.

이 메모에서는 이러한 다른 메모의 개념이나 정의에 대한 사양을 반복하지 않습니다.  가능한 경우 이러한 개념 또는 정의의 사양을 제공하는 메모를 참조합니다.

== iCalendar Object Specification

다음 섹션에서는 캘린더 및 스케줄링 코어 객체 사양의 세부사항을 정의합니다.  캘린더 및 스케줄링 코어 개체는 캘린더 및 스케줄링 정보의 모음입니다.  일반적으로 이 정보는 하나 이상의 iCalendar 개체가 있는 iCalendar 스트림으로 구성됩니다.  iCalendar 객체의 본문은 일련의 캘린더 속성과 하나 이상의 캘린더 구성 요소로 구성됩니다.

3.1절에서는 콘텐츠 줄 형식을 정의하고, 3.2절에서는 속성 매개변수 형식을 정의하고, 3.3절에서는 속성 값의 데이터 형식을 정의하고, 3.4절에서는 iCalendar 개체 형식을 정의하고, 3.5절에서는 iCalendar 속성 형식을 정의하고, 3.6절에서는 캘린더 구성요소 형식을 정의하고, 3.7절에서는 캘린더 속성을 정의하고, 3.8절에서는 캘린더 구성요소의 속성을 정의합니다.

이 정보는 MIME 콘텐츠 유형 등록의 필수적인 부분입니다.  또한 이 정보는 이러한 콘텐츠 등록과 무관하게 사용할 수 있습니다.  특히 이 메모는 파일, 메모리 또는 네트워크 기반 전송 메커니즘에서 캘린더 및 스케줄링 교환 형식으로 사용하기 위해 직접 적용할 수 있습니다.

=== Content Lines

iCalendar 개체는 내용 줄이라고 하는 개별 텍스트 줄로 구성됩니다.  콘텐츠 줄은 줄 바꿈으로 구분되며, 줄 바꿈은 CRLF 시퀀스(CR 문자 다음에 LF 문자)입니다.

텍스트 줄은 줄 바꿈을 제외하고 75옥텟을 넘지 않아야 합니다.  긴 콘텐츠 줄은 줄 '접기' 기법을 사용하여 여러 줄로 나눠서 표시해야 합니다.  즉, 긴 줄 바로 뒤에 단일 선형 공백 문자(예: SPACE 또는 HTAB)를 삽입하여 긴 줄을 두 문자로 분할할 수 있습니다.  콘텐츠 유형을 처리할 때 단일 선형 공백 문자가 바로 뒤에 오는 모든 CRLF 시퀀스는 무시됩니다(즉, 제거됩니다).

예를 들어, 줄입니다:

[source]
----
DESCRIPTION:This is a long description that exists on a long line.
----

다음과 같이 표현할 수 있습니다:

[source]
----
DESCRIPTION:This is a lo
 ng description
  that exists on a long line.
----

이 접힌 여러 줄 표현에서 한 줄 표현으로 이동하는 과정을 "펼치기"라고 합니다.  펼치기는 CRLF와 바로 뒤에 오는 선형 공백 문자를 제거하여 수행됩니다.

콘텐츠 줄을 구문 분석할 때 접힌 줄은 반드시 위에 설명된 펼치기 절차에 따라 먼저 펼쳐야 합니다.

[NOTE]
====
매우 간단한 구현에서는 UTF-8 다중 옥텟 시퀀스 중간에 부적절하게 접힌 줄이 생성될 수 있습니다.  따라서 구현에서는 원래 시퀀스를 올바르게 복원할 수 있는 방식으로 줄을 펼쳐야 합니다.
====

iCalendar 객체와 관련된 콘텐츠 정보는 [RFC2425]에 정의된 것과 유사한 구문을 사용하여 형식이 지정됩니다.  즉, 콘텐츠 정보는 CRLF로 구분된 콘텐츠 줄로 구성됩니다.

다음 표기법은 iCalendar 개체의 콘텐츠 줄을 정의합니다:

[source]
----
contentline   = name *(";" param ) ":" value CRLF
; This ABNF is just a general definition for an initial parsing
; of the content line into its property name, parameter list,
; and value string

; When parsing a content line, folded lines MUST first
; be unfolded according to the unfolding procedure
; described above.  When generating a content line, lines
; longer than 75 octets SHOULD be folded according to
; the folding procedure described above.

name          = iana-token / x-name

iana-token    = 1*(ALPHA / DIGIT / "-")
; iCalendar identifier registered with IANA

x-name        = "X-" [vendorid "-"] 1*(ALPHA / DIGIT / "-")
; Reserved for experimental use.

vendorid      = 3*(ALPHA / DIGIT)
; Vendor identification

param         = param-name "=" param-value *("," param-value)
; Each property defines the specific ABNF for the parameters
; allowed on the property.  Refer to specific properties for
; precise parameter ABNF.

param-name    = iana-token / x-name

param-value   = paramtext / quoted-string

paramtext     = *SAFE-CHAR

value         = *VALUE-CHAR

quoted-string = DQUOTE *QSAFE-CHAR DQUOTE

QSAFE-CHAR    = WSP / %x21 / %x23-7E / NON-US-ASCII
; Any character except CONTROL and DQUOTE

SAFE-CHAR     = WSP / %x21 / %x23-2B / %x2D-39 / %x3C-7E
           / NON-US-ASCII
; Any character except CONTROL, DQUOTE, ";", ":", ","

VALUE-CHAR    = WSP / %x21-7E / NON-US-ASCII
; Any textual character

NON-US-ASCII  = UTF8-2 / UTF8-3 / UTF8-4
; UTF8-2, UTF8-3, and UTF8-4 are defined in [RFC3629]

CONTROL       = %x00-08 / %x0A-1F / %x7F
; All the controls except HTAB
----

콘텐츠 줄의 속성 값 구성 요소에는 속성별로 고유한 형식이 있습니다.  이 형식에 대한 정의는 각 속성을 설명하는 섹션을 참조하세요.

모든 속성 이름, 속성 매개변수, 열거된 속성 값 및 속성 매개변수 값은 대소문자를 구분하지 않습니다.  그러나 다른 모든 속성 값은 달리 명시되지 않는 한 대소문자를 구분합니다.

==== List and Field Separators

일부 속성 및 매개변수는 값 목록을 허용합니다.  값 목록의 값은 반드시 쉼표로 구분해야 합니다.  목록의 값 순서에는 의미가 없습니다.  따옴표로 묶은 문자열로 지정된 매개변수 값(예: URI 값을 지정하는 값)의 경우 개별 따옴표로 묶은 문자열은 COMMA 문자로 구분됩니다.

일부 속성 값은 여러 부분으로 정의됩니다.  이러한 구조화된 속성 값은 반드시 세미콜론 문자로 값 부분을 구분해야 합니다.

일부 속성은 매개변수 목록을 허용합니다.  속성 매개변수 목록의 각 속성 매개변수는 세미콜론 문자로 구분해야 합니다.

콜론 문자, 세미콜론 문자 또는 콤마 문자가 포함된 값이 있는 속성 매개 변수는 반드시 따옴표로 묶은 텍스트 안에 넣어야 합니다.

예를 들어 다음 속성에서 세미콜론은 속성 매개 변수를 서로 구분하는 데 사용되며 COMMA 문자는 값 목록에서 속성 값을 구분하는 데 사용됩니다.

[source]
----
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT:mailto:
jsmith@example.com

RDATE;VALUE=DATE:19970304,19970504,19970704,19970904
----

==== Multiple Values

iCalendar 객체에 정의된 일부 속성은 여러 값을 가질 수 있습니다.  다중 값 항목을 인코딩하는 일반적인 규칙은 속성 이름을 포함하여 각 값에 대해 새 콘텐츠 줄을 만드는 것입니다.  그러나 일부 속성은 값을 쉼표 문자로 구분하여 단일 속성에서 여러 값을 인코딩하는 것을 지원합니다.  특정 속성이 여러 값을 허용하는지 여부와 이 두 가지 형식 중 어떤 형식을 허용하는지 확인하려면 개별 속성 정의를 참조해야 합니다.  다중 값 속성을 사용하여 동일한 값의 여러 언어 변형을 지정해서는 안 됩니다.  캘린더 애플리케이션은 모든 값을 표시해야 합니다.

==== Binary Content

iCalendar 객체의 바이너리 콘텐츠 정보는 속성 값 내의 URI를 사용하여 참조해야 합니다.  즉, 바이너리 콘텐츠 정보는 iCalendar 객체 내에서 URI로 참조할 수 있는 외부 MIME 엔티티에 배치되어야 합니다.  이것이 가능하지 않은 애플리케이션에서는 바이너리 콘텐츠 정보를 [RFC4648]에 정의된 "BASE64" 인코딩 방법을 사용하여 먼저 텍스트로 인코딩한 후에만 iCalendar 객체 내에 포함할 수 있습니다.  인라인 바이너리 콘텐츠는 특별한 상황에서 iCalendar 개체를 단일 엔티티로 표현해야 하는 애플리케이션에서만 사용해야 합니다.  인라인 바이너리 콘텐츠 정보를 포함하는 속성에는 반드시 "ENCODING" 속성 매개변수를 지정해야 합니다. iCalendar 객체 외부에 배치된 바이너리 콘텐츠 정보는 유니폼 리소스 식별자(URI)로 참조되어야 합니다.

다음 예는 URI 참조를 사용하여 iCalendar 객체 외부의 첨부 파일을 참조하는 "ATTACH" 속성을 지정합니다:

[source]
----
ATTACH:http://example.com/public/quarterly-report.doc
----

다음 예제에서는 인라인 바이너리 인코딩된 콘텐츠 정보가 포함된 "ATTACH" 속성을 지정합니다:

[source]
----
ATTACH;FMTTYPE=text/plain;ENCODING=BASE64;VALUE=BINARY:VGhlIH
 F1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZy4
----

==== Character Set

속성 값에 사용되는 문자셋을 선언하는 속성 매개변수는 없습니다.  iCalendar 스트림의 기본 문자셋은 [RFC3629]에 정의된 대로 UTF-8입니다.

사용 중인 문자셋을 지정하려면 MIME 전송에서 "charset" Content-Type 매개변수를 사용해야 합니다.

=== Property Parameters

속성에는 속성과 연관된 속성이 있을 수 있습니다.  이러한 "속성 매개변수"에는 속성 또는 속성 값에 대한 메타 정보가 포함됩니다.  속성 매개변수는 속성 값의 대체 텍스트 표현 위치, 텍스트 속성 값의 언어, 속성 값의 값 유형 및 기타 속성과 같은 정보를 지정하기 위해 제공됩니다.

콜론, 세미콜론 또는 콤마 문자 구분 기호가 포함된 속성 매개변수 값은 반드시 따옴표로 묶인 문자열 텍스트 값으로 지정해야 합니다. 속성 매개 변수 값에는 DQUOTE 문자가 포함되어서는 안 됩니다.  DQUOTE 문자는 제한된 문자 또는 URI 텍스트가 포함된 매개변수 값의 구분 기호로 사용됩니다.  예를 들어

[source]
----
DESCRIPTION;ALTREP="cid:part1.0001@example.org":The Fall'98 Wild
  Wizards Conference - - Las Vegas\, NV\, USA
----

따옴표로 묶이지 않은 속성 매개변수 값은 대소문자를 구분하지 않습니다.

이 메모에서 정의하는 일반적인 속성 매개변수는 다음과 같은 표기법으로 정의됩니다:

[source]
----
icalparameter = altrepparam       ; Alternate text representation
              / cnparam           ; Common name
              / cutypeparam       ; Calendar user type
              / delfromparam      ; Delegator
              / deltoparam        ; Delegatee
              / dirparam          ; Directory entry
              / encodingparam     ; Inline encoding
              / fmttypeparam      ; Format type
              / fbtypeparam       ; Free/busy time type
              / languageparam     ; Language for text
              / memberparam       ; Group or list membership
              / partstatparam     ; Participation status
              / rangeparam        ; Recurrence identifier range
              / trigrelparam      ; Alarm trigger relationship
              / reltypeparam      ; Relationship type
              / roleparam         ; Participation role
              / rsvpparam         ; RSVP expectation
              / sentbyparam       ; Sent by
              / tzidparam         ; Reference to time zone object
              / valuetypeparam    ; Property value data type
              / other-param

other-param   = (iana-param / x-param)

iana-param  = iana-token "=" param-value *("," param-value)
; Some other IANA-registered iCalendar parameter.

x-param     = x-name "=" param-value *("," param-value)
; A non-standard, experimental parameter.
----

애플리케이션은 인식하지 못하는 x-param 및 iana-param 값을 무시해야 합니다.

==== Alternate Text Representation

Parameter Name:: ALTREP

Purpose:: 속성 값에 대한 대체 텍스트 표현을 지정합니다.

Format Definition:: 이 속성 매개변수는 다음 표기법으로 정의됩니다:
+
[source]
----
altrepparam = "ALTREP" "=" DQUOTE uri DQUOTE
----

Description:: 이 매개변수는 텍스트 속성 값의 대체 표현을 가리키는 URI를 지정합니다.  이 매개변수를 지정하는 속성에는 텍스트 값의 기본 표현을 반영하는 값도 포함되어야 합니다.  URI 매개변수 값은 반드시 따옴표로 묶인 문자열로 지정해야 합니다.
+
[NOTE]
====
이 매개변수에 허용되는 URI 스키마에 대한 제한은 없지만, 현재 구현에서 가장 일반적으로 사용되는 URI 스키마는 CID(콘텐츠 식별자) [RFC2392], HTTP [RFC2616] 및 HTTPS [RFC2818]입니다.
====

Example::
+
[source]
----
DESCRIPTION;ALTREP="CID:part3.msg.970415T083000@example.com":
 Project XYZ Review Meeting will include the following agenda
  items: (a) Market Overview\, (b) Finances\, (c) Project Man
 agement
----
+
"ALTREP" 속성 매개변수 값은 "text/html" 콘텐츠 부분을 가리킬 수 있습니다.
+
[source]
----
Content-Type:text/html
Content-Id:<part3.msg.970415T083000@example.com>

<html>
 <head>
  <title></title>
 </head>
 <body>
   <p>
     <b>Project XYZ Review Meeting</b> will include
     the following agenda items:
     <ol>
       <li>Market Overview</li>
       <li>Finances</li>
       <li>Project Management</li>
     </ol>
   </p>
 </body>
</html>
----

==== Common Name

Parameter Name:: CN

Purpose:: To specify the common name to be associated with the calendar user specified by the property.

Format Definition:: This property parameter is defined by the following notation:
+
[source]
----
cnparam    = "CN" "=" param-value
----

Description:: 이 매개 변수는 CAL-ADDRESS 값 유형이 있는 속성에서 지정할 수 있습니다.  이 매개 변수는 속성에서 지정한 캘린더 사용자와 연결할 일반 이름을 지정합니다. 매개변수 값은 텍스트입니다.  이 매개변수 값은 속성에서 지정한 캘린더 주소와 연결할 표시 텍스트에 사용할 수 있습니다.

Example::
+
[source]
----
ORGANIZER;CN="John Smith":mailto:jsmith@example.com
----

==== Calendar User Type

Parameter Name:: CUTYPE

==== Delegators

Parameter Name:: DELEGATED-FROM

==== Delegatees

Parameter Name:: DELEGATED-TO

==== Directory Entry Reference

Parameter Name:: DIR

==== Inline Encoding

Parameter Name:: ENCODING

==== Format Type

Parameter Name:: FMTTYPE

==== Free/Busy Time Type

Parameter Name:: FBTYPE

==== Language

Parameter Name:: LANGUAGE

==== Group or List Membership

Parameter Name:: MEMBER

==== Participation Status

Parameter Name:: PARTSTAT

==== Recurrence Identifier Range

Parameter Name:: RANGE

==== Alarm Trigger Relationship

Parameter Name:: RELATED

==== Relationship Type

Parameter Name:: RELTYPE

==== Participation Role

Parameter Name:: ROLE

==== RSVP Expectation

Parameter Name:: RSVP

==== Sent By

Parameter Name:: SENT-BY

==== Time Zone Identifier

Parameter Name:: TZID

==== Value Data Types

Parameter Name:: VALUE

=== Property Value Data Types

iCalendar 개체의 속성은 강력하게 유형화되어 있습니다.  각 속성의 정의는 값이 이 섹션에 정의된 값 데이터 유형 또는 단순히 값 유형 중 하나로 제한됩니다. 속성의 값 유형은 기본 값 유형으로 암시적으로 지정되거나 "VALUE" 매개변수를 사용하여 명시적으로 지정됩니다.  속성의 값 유형이 대체 유효한 유형 중 하나인 경우 "VALUE" 매개 변수를 사용하여 명시적으로 지정해야 합니다.

==== Binary

Value Name:: BINARY

==== Boolean

Value Name:: BOOLEAN

==== Calendar User Address

Value Name:: CAL-ADDRESS

==== Date

Value Name:: CAL-ADDRESS

==== Date-Time

Value Name:: DATE-TIME

==== Duration

Value Name:: DURATION

==== Float

Value Name:: FLOAT

==== Integer

Value Name:: INTEGER

==== Period of Time

Value Name:: PERIOD

==== Recurrence Rule

Value Name:: RECUR

Purpose:: 이 value type은 반복 규칙 사양이 포함된 속성을 식별하는데 사용한다.

Format Definition::
+
[source]
----
recur           = recur-rule-part *( ";" recur-rule-part )
               ;
               ; The rule parts are not ordered in any
               ; particular sequence.
               ;
               ; The FREQ rule part is REQUIRED,
               ; but MUST NOT occur more than once.
               ;
               ; The UNTIL or COUNT rule parts are OPTIONAL,
               ; but they MUST NOT occur in the same 'recur'.
               ;
               ; The other rule parts are OPTIONAL,
               ; but MUST NOT occur more than once.

recur-rule-part = ( "FREQ" "=" freq )
               / ( "UNTIL" "=" enddate )
               / ( "COUNT" "=" 1*DIGIT )
               / ( "INTERVAL" "=" 1*DIGIT )
               / ( "BYSECOND" "=" byseclist )
               / ( "BYMINUTE" "=" byminlist )
               / ( "BYHOUR" "=" byhrlist )
               / ( "BYDAY" "=" bywdaylist )
               / ( "BYMONTHDAY" "=" bymodaylist )
               / ( "BYYEARDAY" "=" byyrdaylist )
               / ( "BYWEEKNO" "=" bywknolist )
               / ( "BYMONTH" "=" bymolist )
               / ( "BYSETPOS" "=" bysplist )
               / ( "WKST" "=" weekday )

freq        = "SECONDLY" / "MINUTELY" / "HOURLY" / "DAILY"
           / "WEEKLY" / "MONTHLY" / "YEARLY"

enddate     = date / date-time

byseclist   = ( seconds *("," seconds) )

seconds     = 1*2DIGIT       ;0 to 60

byminlist   = ( minutes *("," minutes) )

minutes     = 1*2DIGIT       ;0 to 59

byhrlist    = ( hour *("," hour) )

hour        = 1*2DIGIT       ;0 to 23

bywdaylist  = ( weekdaynum *("," weekdaynum) )

weekdaynum  = [[plus / minus] ordwk] weekday

plus        = "+"

minus       = "-"

ordwk       = 1*2DIGIT       ;1 to 53

weekday     = "SU" / "MO" / "TU" / "WE" / "TH" / "FR" / "SA"
;Corresponding to SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY,
;FRIDAY, and SATURDAY days of the week.

bymodaylist = ( monthdaynum *("," monthdaynum) )

monthdaynum = [plus / minus] ordmoday

ordmoday    = 1*2DIGIT       ;1 to 31

byyrdaylist = ( yeardaynum *("," yeardaynum) )

yeardaynum  = [plus / minus] ordyrday

ordyrday    = 1*3DIGIT      ;1 to 366

bywknolist  = ( weeknum *("," weeknum) )

weeknum     = [plus / minus] ordwk

bymolist    = ( monthnum *("," monthnum) )

monthnum    = 1*2DIGIT       ;1 to 12

bysplist    = ( setposday *("," setposday) )

setposday   = yeardaynum
----

Description:: 이 value type은 하나 혹은 여러개의 recurrence grammar part 목록으로 구성된 구조화된 값이다. 각 규칙 부분(rule part)는 `NAME=VALUE` 쌍으로 정의되며, 세미콜론으로 구분하고, 특정 순서로 정렬되지 않는다. 개별 규칙 부분은 한 번만 지정해야 한다(**MUST**). 호환 응용프로그램은 규칙 부분의 순서와 상관없이 받아들여야 하지만, iCalendar의 리비전의 이전 버전의 응용프로그램과의 하위 호환성을 보장하기 위해 `FREQ` 규칙 부분은 `RECUR` 값에 첫번째 규칙 부분이어야 한다(**MUST**).

`FREQ` 규칙 파트는 ...

Example:: 격일로 10회를 나타내는 규칙
+
[source]
----
FREQ=DAILY;COUNT=10;INTERVAL=2
----

==== Text

Value Name:: TEXT

==== Time

Value Name:: TIME

==== URI

Value Name:: URI

==== UTC offset

Value Name:: UTC-OFFSET

* 목적: UTC에서 local-time까지의 offset이 포함된 프로퍼티.
* 형식 정의:
+
[source]
----
utc-offset = time-numzone
time-numzone = ("+" / "-") time-hour time-minute [time-second]
----
* 설명: `+` 는 **반드시** UTC 앞의 값을 표시. `-` 는 **반드시** UTC 뒷 값을 표시. `-0000`, `-000000` 과 같은 값은 허용하지 않음.
시간초가 있을 경우 이 값은 60이어서는 안되며, 기본값은 0입니다.
이 값에는 추가 컨텐츠 값은 정의되지 않음.
* 예제
+
[source]
----
-0500
+0100
----

=== iCalendar Object

=== Property

=== Calendar Components

==== Free/Busy Component

* 컴포넌트명: VFREEBUSY
* 목적: free/busy time 요청 혹은 응답과 publish된 busy time 셋을 설명하는 컴포넌트 속성들의 그룹을 제공한다.
* 포맷 정의
+
[source]
----
freebusyc  = "BEGIN" ":" "VFREEBUSY" CRLF
             fbprop
             "END" ":" "VFREEBUSY" CRLF

fbprop     = *(
             ;
             ; The following are REQUIRED,
             ; but MUST NOT occur more than once.
             ;
             dtstamp / uid /
             ;
             ; The following are OPTIONAL,
             ; but MUST NOT occur more than once.
             ;
             contact / dtstart / dtend /
             organizer / url /
             ;
             ; The following are OPTIONAL,
             ; and MAY occur more than once.
             ;
             attendee / comment / freebusy / rstatus / x-prop /
             iana-prop
             ;
             )
----
* 설명
** "VFREEBUSY" 캘린더 컴포넌트는 free/busy time 정보의 요청, 요청에 대한 응답, busy time 정보를 게시하는 셋을 표현하는 컴포넌트 속성의 그룹이다.
** free/busy time 정보 요청할 때 각 프로퍼티는 다음과 같다.
*** "ATTENDEE" 프로퍼티는 free/busy time이 요청되는 캘린더 유저를 나타낸다.
*** "ORGANIZER" 프로퍼티는 free/busy time을 요청하는 캘린더 유저를 나타낸다.
*** "DTSTART", "DTEND" 프로퍼티는 free/busy time이 요청되는 시간 window를 나타낸다.
*** "UID", "DTSTAMP" 프로퍼티는 여러 약속 있음/없음 시간 요청들의 적절한 순서를 지원하도록 기술한다.
** When used to reply to a request for free/busy time, the "ATTENDEE" property specifies the calendar user responding to the free/busy time request; the "ORGANIZER" property specifies the calendar user that originally requested the free/busy time; the "FREEBUSY" property specifies the free/busy time information (if it exists); and the "UID" and "DTSTAMP" properties are specified to assist in proper sequencing of multiple free/busy time replies.
** When used to publish busy time, the "ORGANIZER" property specifies the calendar user associated with the published busy time; the "DTSTART" and "DTEND" properties specify an inclusive time window that surrounds the busy time information; the "FREEBUSY" property specifies the published busy time information; and the "DTSTAMP" property specifies the DATE TIME that iCalendar object was created.
** The "VFREEBUSY" calendar component cannot be nested within another calendar component.  Multiple "VFREEBUSY" calendar components can be specified within an iCalendar object.  This permits the grouping of free/busy information into logical collections, such as monthly groups of busy time information.
** The "VFREEBUSY" calendar component is intended for use in iCalendar object methods involving requests for free time, requests for busy time, requests for both free and busy, and the associated replies.
** Free/Busy information is represented with the "FREEBUSY" property. This property provides a terse representation of time periods. One or more "FREEBUSY" properties can be specified in the "VFREEBUSY" calendar component.
** When present in a "VFREEBUSY" calendar component, the "DTSTART" and "DTEND" properties SHOULD be specified prior to any "FREEBUSY" properties.
** The recurrence properties ("RRULE", "RDATE", "EXDATE") are not permitted within a "VFREEBUSY" calendar component.  Any recurring events are resolved into their individual busy time periods using the "FREEBUSY" property.
* 예시
+
[source]
----
BEGIN:VFREEBUSY
UID:19970901T082949Z-FA43EF@example.com
ORGANIZER:mailto:jane_doe@example.com
ATTENDEE:mailto:john_public@example.com
DTSTART:19971015T050000Z
DTEND:19971016T050000Z
DTSTAMP:19970901T083000Z
END:VFREEBUSY
----
+
[source]
.busy time 정보 요청의 응답에 사용되는 "VFREEBUSY" 캘린더 컴포넌트 예시
----
BEGIN:VFREEBUSY
UID:19970901T095957Z-76A912@example.com
ORGANIZER:mailto:jane_doe@example.com
ATTENDEE:mailto:john_public@example.com
DTSTAMP:19970901T100000Z
FREEBUSY:19971015T050000Z/PT8H30M,
 19971015T160000Z/PT5H30M,19971015T223000Z/PT6H30M
URL:http://example.com/pub/busy/jpublic-01.ifb
COMMENT:This iCalendar file contains busy time information for
 the next three months.
END:VFREEBUSY
----
+
[source]
.busy time 정보를 게시하는데 사용되는 "VFREEBUSY" 캘린더 컴포넌트 예시
----
BEGIN:VFREEBUSY
UID:19970901T115957Z-76A912@example.com
DTSTAMP:19970901T120000Z
ORGANIZER:jsmith@example.com
DTSTART:19980313T141711Z
DTEND:19980410T141711Z
FREEBUSY:19980314T233000Z/19980315T003000Z
FREEBUSY:19980316T153000Z/19980316T163000Z
FREEBUSY:19980318T030000Z/19980318T040000Z
URL:http://www.example.com/calendar/busytime/jsmith.ifb
END:VFREEBUSY
----


=== Calendar Properties

=== Component Properties

==== Recurrence Component Properties

===== Exception Date-Times

===== Recurrence Date-Times

===== Recurrence Rule

|===
| **Property Name** | `RRULE`
| **Value Name** | `RECUR`
|===

Purpose: 이 속성은 반복 이벤트, 할 일, 업무 일지 또는 표준 시간대 정의에 대한 규칙 또는 반복 패턴을 정의합니다.

Property Parameters: IANA 및 비표준 속성 매개변수를 이 속성에 지정할 수 있습니다.

Conformance: 이 프로퍼티는 반복되는 "VEVENT", "VTODO" 및 "VJOURNAL" 캘린더 컴포넌트와 "VTIMEZONE" 캘린더 컴포넌트의 "STANDARD" 및 "DAYLIGHT" 하위 컴포넌트에서 지정할 수 있습니다. 그러나, 2번 이상 지정되서는 안됩니다. 여러 "RRULE" 속성으로 생성된 recurrence set은 정의되지 않았습니다.

Format Definition:  This property is defined by the following notation:

[source]
----
rrule      = "RRULE" rrulparam ":" recur CRLF

rrulparam  = *(";" other-param)
----

Description:

예시:

[NOTE]
.Eastern Time(ET): EST and EDT
====
EST:: Eastern Standard Time. GMT-5
EDT:: Eastern Daylight Time. GMT-4
====

[source]
.'1997/09/02 09:00:00'부터 매일 총 10번 반복
----
DTSTART;TZID=America/New_York:19970902T090000
RRULE:FREQ=DAILY;COUNT=10

==> (1997 9:00 AM EDT) September 2-11
----

[source]
.'1997/09/02 09:00:00'부터 '1997/12/24'까지 매일 반복
----
DTSTART;TZID=America/New_York:19970902T090000
RRULE:FREQ=DAILY;UNTIL=19971224T000000Z

==> (1997 9:00 AM EDT) September 2-30;October 1-25
    (1997 9:00 AM EST) October 26-31;November 1-30;December 1-23
----

[source]
.'1997/09/02 09:00:00'부터 격일로 영원히 반복
----
DTSTART;TZID=America/New_York:19970902T090000
RRULE:FREQ=DAILY;INTERVAL=2

==> (1997 9:00 AM EDT) September 2,4,6,8...24,26,28,30;
                       October 2,4,6...20,22,24
    (1997 9:00 AM EST) October 26,28,30;
                       November 1,3,5,7...25,27,29;
                       December 1,3,...
----

[source]
.'1997/09/02 09:00:00'부터 10일마다 총 5번 반복
----
DTSTART;TZID=America/New_York:19970902T090000
RRULE:FREQ=DAILY;INTERVAL=10;COUNT=5

==> (1997 9:00 AM EDT) September 2,12,22;
                       October 2,12
----

[source]
.'1998/01/01 09:00:00'부터 매년 1월내내 3년동안 반복
----
DTSTART;TZID=America/New_York:19980101T090000

RRULE:FREQ=YEARLY;UNTIL=20000131T140000Z;
 BYMONTH=1;BYDAY=SU,MO,TU,WE,TH,FR,SA
or
RRULE:FREQ=DAILY;UNTIL=20000131T140000Z;BYMONTH=1

==> (1998 9:00 AM EST)January 1-31
    (1999 9:00 AM EST)January 1-31
    (2000 9:00 AM EST)January 1-31
----

[source]
.'1997/09/02 09:00:00'부터 매주 총 10번 반복
----
DTSTART;TZID=America/New_York:19970902T090000
RRULE:FREQ=WEEKLY;COUNT=10

==> (1997 9:00 AM EDT) September 2,9,16,23,30;October 7,14,21
    (1997 9:00 AM EST) October 28;November 4
----

[source]
.'1997/09/02 09:00:00'부터 '1997/12/24'까지 매주 반복
----
DTSTART;TZID=America/New_York:19970902T090000
RRULE:FREQ=WEEKLY;UNTIL=19971224T000000Z

==> (1997 9:00 AM EDT) September 2,9,16,23,30;
                       October 7,14,21
    (1997 9:00 AM EST) October 28;
                       November 4,11,18,25;
                       December 2,9,16,23
----


https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.5.3

== iCalendar Object Examples

'1996/09/18 14:30 UTC'에 시작하여 '1996/09/20 22:00 UTC'에 끝나는 3일 회의를 지정할 경우.

[source]
----
BEGIN:VCALENDAR
PRODID:-//xyz Corp//NONSGML PDA Calendar Version 1.0//EN
VERSION:2.0
BEGIN:VEVENT
DTSTAMP:19960704T120000Z
UID:uid1@example.com
ORGANIZER:mailto:jsmith@example.com
DTSTART:19960918T143000Z
DTEND:19960920T220000Z
STATUS:CONFIRMED
CATEGORIES:CONFERENCE
SUMMARY:Networld+Interop Conference
DESCRIPTION:Networld+Interop Conference
  and Exhibit\nAtlanta World Congress Center\n
 Atlanta\, Georgia
END:VEVENT
END:VCALENDAR
----

== Recommended Practices
