= spring-data-jdbc

[plantuml]
....
@startuml

interface JdbcOperation {
  query(psc, rowMapper): List<T>
}
class JdbcTemplate

interface NamedParameterJdbcOperations
class NamedParameterJdbcTemplate {
  -classicJdbcTemplate: JdbcOperations
}


JdbcOperation <|-- JdbcTemplate
NamedParameterJdbcOperations <|-- NamedParameterJdbcTemplate

NamedParameterJdbcTemplate --> JdbcOperation

@enduml
....

* DataSource: 접속 정보
* JdbcTemplate: 
* JdbcOperation: 구현체
* NamedParameterJdbcTemplate
* TransactionManager
* TransactionTemplate
* DataAccessStrategy
* ResultMap

== findById

. `CrudRepository` 구현체인 `SimpleJdbcRepository`
.. `JdbcAggregateOperations` 필드의 `findById` 메서드 실행됨
.. `JdbcAggregateOperations` 구현체인 `JdbcAggregateTemplate`
... `DataAccessStrategy` 필드의 `findById` 메서드 호출
.... `DataAccessStrategy` 구현체인 `DefaultDataAccessStrategy`
.... `SqlGeneratorSource` 필드의 `getSqlGenerator` 메서드 통해서 쿼리 생성
.... `SqlParamgersFactory` 필드의 `forQueryById` 메서드 통해서 쿼리 파라미터 생성
.... `getEntityRowMapper` 메서드 통해 `RowMapper` 생성
.... `operations: NamedParameterJdbcOperations` 필드의 `queryForObject` 메서드 통해서 쿼리 실행 (w/ rowMapper)
..... `converter: JdbcConverter` 필드의 `query` 메서드 호출
..... `execute` 메서드 호출
..... `DateSourceUtils.getConnection(DataSource)` 메서드 통해서 `Connection` 생성
... `triggerAfterConvert` 메서드 실행
