= Transation

[plantuml]
....
@startuml
skinparam defaultFontName "NanumGothic"

package org.springframwork.transaction {
  interface TransationManager
  interface PlatformTransactionManager
  interface ReactiveTransactionManager
  
  package org.springframwork.transaction.support {
    interface ResourceTransactionManager
    abstract class AbstractPlatformTransactionManager
    abstract class AbstractReactiveTransactionManager
  }
  
  package org.springframework.transaction.annotation {
    annotation Transactional
  }

  TransationManager <|-- PlatformTransactionManager
  TransationManager <|-- ReactiveTransactionManager
  PlatformTransactionManager <|-- ResourceTransactionManager
  PlatformTransactionManager <|-- AbstractPlatformTransactionManager
}

package org.springframework.jdbc {
  package org.springframework.jdbc.datasource {
    class DataSourceTransactionManager
  }

  package org.springfremework.jdbc.support {
    class JdbcTransactionManager 
  }
}

package org.springframework.orm.jpa {
  class JpaTransactionManager
}

AbstractPlatformTransactionManager <|-- DataSourceTransactionManager
ResourceTransactionManager <|-- DataSourceTransactionManager
DataSourceTransactionManager <|-- JdbcTransactionManager 

AbstractPlatformTransactionManager <|-- JpaTransactionManager
ResourceTransactionManager <|-- JpaTransactionManager

@enduml
....

* `PlatformTransactionManager`: 트랜잭션의 경계를 지정하는데 사용. `commit`, `rollback` 인터페이스
* https://kouzie.github.io/spring/Spring-%EC%8A%A4%ED%94%84%EB%A7%81-%ED%8A%B8%EB%9E%9C%EC%9E%AD%EC%85%98/#
