= Credentials

https://support.cloudbees.com/hc/en-us/articles/222978868-How-to-Connect-to-Remote-SSH-Agents-

== Github 연결


=== id/pw

. 'Credentials' > 'System' > 'Global credentials' > 'Add Credentials' 이동
. Kind에 'Username with password'로 추가
. 'Manage Jenkins' > 'Configure System' 에서 Github 까지 이동
. 여기서 가장 아래에 '고급' 선택 후 'Additional action'에 'Convert login and password to token' 선택
. 'Create token credentials' 를 클릭하면 github과 jenkins에 자동으로 추가됨
. 다시 'Manage Jenkins' > 'Configure System' 에서 Github 까지 이동 후 위에서 추가한 token 인증으로 설정
. git repository에 jenkins에서 접근 하는 계정의 권한을 추가('Setting' > 'Collaborators & teams')

=== ssh

. Jenkins에 Github integration plugin 설치
. 서버에서 sshkey 생성
. pub 키를 github에 추가 (Settings -> Deploy keys)
. private 키는 jenkins에 추가(Add Credentials -> Kind: SSH Username with private key)
** Username: job에서 보여줄 인증키 
. Create new item
** Add repository URL: `git@github.com:user/repo.git`
. webhook 추가(Settings -> Hooks)
** Payload URL: `<jenkins url>/github-webhook/` +
   마지막에 슬래쉬 붙여줘야 함 -> https://stackoverflow.com/a/49118822/3793078


== New Item (pipeline)

. Jenkins -> 'New Item'
. Select 'Pipeline'
** 'Build Triggers'
*** Check 'GitHub hook trigger for GITScm polling'
** 'Pipeline'
*** Definition: Pipeline script from SCM
*** SCM: Git
. Job을 한번 실행시켜줘야 다음부터 hook을 받음

== Node 추가

. ssh key 생성
+
[source, bash]
----
$ ssh <server>
$ mkdir ~/.ssh && chmod 700 ~/.ssh
$ cd ~/.ssh

$ ssh-keygen -t rsa -C "Jenkins agent key" -f "jenkinsAgent_rsa"
$ cat jenkinsAgent_rsa.pub >> ~/.ssh/authorized_keys

# private key 복사 후 jenkins에 등록
$ cat jenkinsAgent_rsa
----

. credentials 생성
.. `Add Credentials` 로 추가
*** Username: 접속하고자 하는 서버의 계정
*** Private Key: 서버에서 생성한 private key
*** Passphrase: ssh key 생성시 입력한 passphrase

. node 추가
** `# of executors` 갯수는 전체 코어 갯수보다 적게 설정해야 한다. -> `lscpu` 명령어로 cpu 정보 확인 가능
