= PlantUML
:toc:

== 시작하기

* https://drawio-app.com/use-plantuml-in-draw-io/[Use PlantUML in draw.io]
+
but, "Note: draw.io for Confluence Server and data center do not support PlantUML."
* Jira
** https://marketplace.atlassian.com/apps/41025/plantuml-for-confluence[PlantUML for Confluence]
** https://marketplace.atlassian.com/apps/1215115/plantuml-diagrams-for-confluence[**PlantUML Diagrams for Confluence**]


github action: https://github.com/grassedge/generate-plantuml-action

<<<

== Class diagram

|===
| https://plantuml.com/ko/class-diagram 
|===

* 일반화^generalization^: `--|>`
* 실체화^Realization^: `..|>`
* 의존^dependency^: `..>`
* 연관^association^: `--`
* 직접 연관^directed{sp}association^: `-->`
* 집합^aggregation^, 집합 연관: `o--`, `o-->`
* 합성^composition^, 복합 연관: `\*--`, `*-->`

=== Generalization

* 일반화, 상속 구조
* "is a kine of" 관계
* overriding되면 서브 클래스에 해당 함수/필드를 정의

++++
<table>
++++

++++
<tr><td>
++++

[plantuml]
....
@startuml
hide empty field
hide empty method

class User {
  +isHead(): Boolean
}
class HeadUser {
  +isHead(): Boolean
}
class AdminUser

User <|-- HeadUser
User <|-- AdminUser
@enduml
....

++++
</td><td>
++++

[source, kotlin]
----
class User {
  fun isHead(): Boolean = false
}
class HeadUser: User() {
  override fun isHead(): Boolean = true
}
class AdminUser: User()
----

++++
</td></tr>
++++


++++
</table>
++++

=== Realization

* interface에 있는 명세를 오버라이딩하여 구현하는 것
* "can do this" 관계
* 두 가지 표현법이 존재함

[plantuml]
.스테레오 타입으로 정의
....
@startuml
hide empty field
hide empty method

class User
interface Changeable {
  +changeNickName(nickName: String): Unit
}
class HeadUser {
  +changeNickName(nickName: String): Unit
}

User <|-- HeadUser
Changeable <|.. HeadUser
@enduml
....

[plantuml]
.circle 형태로 정의
....
@startuml
hide empty field
hide empty method

class User
circle Changeable
class HeadUser {
  +changeNickName(nickName: String): Unit
}

User <|-- HeadUser
Changeable -- HeadUser
@enduml
....

=== Dependency

* 클래스간 참조가 일어나는 것 중 하나
* 메서드 내에서 대상 클래스의 객체를 생성하거나 사용, 리턴 받아 사용하는 것을 말함
* 이 참조는 해당 클래스와의 관계를 계속 유지하지 않음

++++
<table>
++++

++++
<tr><td>
++++

[plantuml]
....
@startuml
hide empty field
hide empty method

class User
interface Changeable {
  +changeNickName(nickName: String): Unit
}
class HeadUser {
  +changeNickName(nickName: String): Unit
  +<b>createSchedule(): Schedule
  +<b>useSchedule(schedule: Schedule): Unit
}
class Schedule

User <|-- HeadUser
Changeable <|.. HeadUser
HeadUser .[dashed,thickness=2].> Schedule
@enduml
....

++++
</td><td>
++++

[source, kotlin]
----
class HeadUser: User, Changeable {
  override fun changeNickName(nickName: String): Unit { ... }

  fun createSchedule(): Schedule {
    return Schedule() // 객체 생성 및 반환
  }
  
  fun useSchedule(schedule: Schedule): Unit {
    // 객체를 매개변수로 받아서 사용
  }
}
----

++++
</td></tr>
++++


++++
</table>
++++

=== Association

* 일반적인 연관은 실선으로 연결
* Directed Association은 실선 후 끝에 화살표 추가

=== Aggregation

* 집합
* Shared Aggregation

[plantuml]
....

....

=== Composition

* Composite Aggregation 이라고도 함
* 강한 집합을 의미

[plantuml]
....

....

== Example

=== 글꼴 지정

[plnatuml]
....
@startuml
skinparam defaultFontName "NanumGothic"

@enduml
....

=== footer 설정

[plnatuml]
....
@startuml
center footer © NAVER FINANCIAL Corp. All Rights Reserved.

@enduml
....

=== 외부 puml 파일 참조하기

[plantuml]
....
include::example-diagram.puml[]
....

=== 다이어그램 가운데 정렬하기

[plantuml,align="center"]
....
@startuml
A -> B
@enduml
....

=== group 배경 투명하게 하기

[plantuml]
.AS-IS
....
@startuml
box "actor1" #lightblue
  participant A
  participant B
end box
participant C

A -> B
group group1
  B -> C
  C --> B
end group
@enduml
....

[plantuml]
.TO-BE
....
@startuml
box "actor1" #lightblue
  participant A
  participant B
end box
participant C

A -> B
group #transparent group1
  B -> C
  C --> B
end group
@enduml
....

[NOTE]
====
2022-02-10, 새로운 스타일 적용되면서 기본 투명으로 적용된 것 같음. https://twitter.com/PlantUML/status/1491847768436060168[ref]
====

=== 이모지 추가

[plantuml]
....
@startuml
A -> B: <:lock:> 잠금
@enduml
....

.References
* https://plantuml.com/ko/creole#68305e25f5788db0
* https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md

== 메모 넣기

[plantuml]
.https://stackoverflow.com/questions/45794732/plantuml-nested-components-with-text-possible/46386222#46386222[ref]
....
@startuml
skinparam rectangle<<desc>> {
    backgroundColor Transparent
    borderColor Transparent
    titleFontColor Red
    stereotypeFontColor Transparent
}

folder folder2 {
    folder folder3 [
        text bla bla
    ]
    artifact art2 [
        more text
    ]
    rectangle f2<<desc>> [
        Here you can have some explanation with
        ====
        --Markdown-- //formatting// ~~elements~~
    ]

    folder3 -[hidden]- f2
}
@enduml
....

[plantuml]
....
@startuml

folder folder2 {
    folder folder3 [
        text bla bla
    ]
    artifact art2 [
        more text
    ]
    
    label "간략한 내용을 남겨높는다" as simple_label
    folder3 -[hidden]down- simple_label
}
@enduml
....

== Trick

include::trick.adoc[]

== Examples

* https://plantuml.info/
* https://real-world-plantuml.com/

== References

* https://www.nextree.co.kr/p6753/
