= 네이밍을 위한 영단어 의미 비교
:toc:

== generate, create, make, insert

create:: 생성(生成). 무에서 유를 만드는 것. 또는 많은 창의성을 발휘해서 무언가 만드는 것.
+
.Examples
* A chef might _create_ a new dish, but after it's been created, he might find himself _making_ it every night.

make:: 11

generate:: 작성(作成). 무언가 만들고 그 효과를 얻는 것. 일련의 단계를 통해 무언가는 생성하는 것.
+
.Examples
* This motro will _generate_ electricty for your house.
* [line-through]#You _generate_ a cake.#

insert:: 어떤 것에 넣는다는 의미로 생성의 의미는 아니며 '데이터데이스(테이블)에 데이터를 넣는다'는 의미로 사용함. 생성의 의미로 볼 수 있지만 이미 만들어진 테이블에 넣는다는 의미로 사용하는 것 같음.
+
* `CREATE TABLE <TABLE> ...`
* `INSERT INTO <TABLE> ...`

<<<
---

* generate 대신 make나 create 사용 가능
* 그러나, make와 create는 동일하지 않음
* 예를 들어, `Generate Video` 버튼은 소프트웨어가 사용자가 설정한 대로 비디오를 만들것을 강조할 수 있는 반면, `Create Video` 는 사용자가 곧 자신의 창작물을 마친다는 것을 강조할 수 있음. +
`Make Video` 도 가능한 예시이며, 이는 세 단어중 가장 간단한 단어로 어린이가 사용할 수 있는 소프트웨어를 만든다는 의미에 적합.

.References
* https://ell.stackexchange.com/questions/76985/create-vs-generate-vs-make

== checkout, payment, order

checkout:: (슈퍼마켓 따위에서의) 계산(대)

payment:: 지불, 납부, 납입

order:: 주문


== user vs. member

== feedback vs. opinion

.feedback
* 피드백은 의견보다 보다 높은?
* 특정 주제나 사건에 대해 어떻게 느꼈는지 설명하는 것
* 요청할 때 제공하는 것
* 서비스나 제품을 개선하거나 변경하는 데 도움이 됨
* 비판적 평가?

.opinion
* 주제나 사건에 대한 당신의 생각을 말하는 것.
* 생각이나 선호도로 표현할 수 있음
* 당신의 지식과 경험을 바탕으로 어떤 것에 대해 내리는 일종의 판단.
* 의견은 합리적이지 않거나 과학적 사실에 근거하지 않을 수 있음. 
* 아무것도 모르는 주제에 대해서도 간단히 의견을 만들수 있음
* 요청 하지 않아도 의견을 낼 수 있음
