= Concurrency Programming
:source-highlighter: coderay
:toc:

====
아래 교재 및 문서를 보고 공부한 내용을 정리한 공간입니다.

* http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9791161754222[코틀린 동시성 프로그래밍]
====

== Hello, Concurrent World!

프로세스::
* 실행중인 어플리케이션의 인스턴스. 즉, 어플리케이션 ∋ 프로세스
* 상태를 갖음
* 최소한 하나의 스레드를 포함

스레드::
* 실행 스레드는 프로세스가 실행할 일련의 명령을 포함
* 대게 GUI 어플리키에션에서 메인 스레드, UI 스레드 등이 있음

코루틴::
* 코틀린이 동싱성을 구현한 방식을 보면 개발자가 직접 스레드를 시작하거나 중지할 필요없다는 것을 알게 됨
* 코루틴^coroutin^을 실행하도록 지시하기만 하면 됨
* 스레드와 관련된 나머지 처리는 프레임워크에 의해 수행 됨

=== 코루틴

* 코틀린 문서에서는 코루틴은 경량 스레드라고 함
** 스레드처럼 프로세서가 실행할 명령어 집합의 실행을 정의하기 때문
** 스레드와 비슷한 라이프 사이클을 가짐
* 코루틴은 스레드 안에서 실행됨
* 코루틴이 특정 스레드에서 실행되더라도 스레드에 묶이지 않음
** 코루틴의 일부를 특정 스레드에서 실행하고, 실행 중지한 뒤 나중에 다른 스레드에서 계속 실행하는 것이 가능

=== 동시성은 병렬성이 아니다

* 병렬 실행^paralled{sp}execution^은 두 스레드가 정확히 같은 시점에 실행될 때만 발행
* 동시 실행^concurrent{sp}execution^은 단일 코어가 서로 다른 스레드의 인스트럭션^instructions,{sp}명령^을 교차 배치해서, 스레드들의 실행을 효율적으로 겹쳐서 실행
** Context switch 발생
* 병렬은 동시성을 의미하지만 동시성은 병렬성이 없이도 발생할 수 있다는 점에 유의
** 분산 컴퓨팅(distributed computing)은 병렬성의 한 형태

[TIP]
====
동시성 코드가 항상 필요하다거나 꼭 이득을 얻는 것이 아님. 코드의 병목과 스레드 및 코루틴의 작동방식과 동시성/병렬성 차이를 이해해 두면 언제 어떻게 구현해야 하는지 판단 가능
====

=== CPU 바운드와 I/O 바운드

* CPU 바운드 알고리즘의 경우 다중 코어에서 병렬성을 활용하면 성능을 향상시킬 수 있음
** but, 단일 코어에서 동시성을 구현하면 성능이 저하되기도 함
*** 예를 들어, 컨텍스트 스위칭으로 인한 오버헤드
*** Context switching은 현재 스레드의 상태를 저장한 후 다음 스레드의 상태를 적재해야하기 때문에 전체 프로세스의 오버헤드가 발생
** CPU 바운드 알고리즘을 위해서는 현재 사용중인 장치의 코어 수를 기준으로 적절한 스레드 수 생성을 고려해야 함
*** CPU 바운드 알고리즘을 실행하기 위해 생성된 스레드 풀인 코틀린의 `CommonPool` 을 활용할 수 있음
(`CommonPool` 크이는 머신의 코어 수에서 1을 뺀 값)
* I/O 작업은 동시성으로 실행하는 편이 좋음
** I/O 바운드 알고리즘은 끊임없이 무언가를 기다림
** 단일 코어 기기에서 대기하는 중에 다른 프로세스를 사용할 수 있게 함

=== 동시성이 어려운 이유

* 동시성 프로그램 자체가 어렵기도 하지만 많은 언어가 이것을 더 어렵게 만들기 때문
* 동시성 코드를 작성할 때 제시되는 공통된 문제점 고려해야 함

==== 레이스 컨디션^Race{sp}conditions:{sp}경합{sp}조건^

* 동시성 코드를 작성할 때 가장 흔한 오류
* 코드를 동시성으로 작성했지만 순차적 코드처럼 동작할 것이라고 예상할 때 발생
* 동시성 코드가 항상 특정한 순서로 실행될 것이라 가정하고 오해할 때 생기는 문제
* 정보에 접근하려고 하기 전에 정보를 얻을 때까지 명시적으로 기다리도록 해야 함

[source, kotlin]
.Example
----
data class UserInfo(val name: String, val lastName: String, val id: Int)

lateinit var user: UserInfo

fun main(args: Array<String>) = runBlocking {
    asyncGetUserInfo(1)
    // Do some other operations
    delay(1000)

    println("User ${user.id} is ${user.name}") // <1>
}

fun asyncGetUserInfo(id: Int) = async {
    user = UserInfo(id = id, name = "Susan", lastName = "Calvin")
}
----
<1> 순차적으로 실행될 것이라고 예상하고 `user` 에 접근. 명시적으로 `asyncGetUserInfo` 함수를 기다도록 해야 함

==== 원자성 위반^atomic{sp}operations^

* 작업이 사용하는 데이터를 간섭 없이 접근할 수 있음을 말함
* 단일 스레드 어플리케이션에서는 모든 코드가 순차적으로 실행되기 때문에 모든 작업이 모두 원자일 것
* 원자성은 객체의 상태가 동시에 수정될 수 있을 때 필요, 상태의 수정이 겹치지 않도록 보장해야 함

[source, kotlin]
.Example
----
var counter = 0 // 원자성 위반
fun main(args: Array<String>) = runBlocking {
    val workerA = asyncIncrement(2000)
    val workerB = asyncIncrement(100)
    workerA.await()
    workerB.await()
    println("counter [$counter]")
}

fun asyncIncrement(by: Int) = GlobalScope.async {
    for(i in 0 until by) {
        counter++
    }
}
----

==== 교착 상태^circular{sp}dependencies^

* 두 작업이 서로를 기다리고 있을 때 누구도 끝나지 않는 상황
* 실제 시나리오에서 교착 상태를 발견하고 수정하기란 어려움
* 레이스 컨디션은 교착 상태가 발생할 수 있는 예기치 않은 상태를 만들기도 함

==== 라이브 락^Livelocks^

* 교착 상태와 유사
* 라이브 락이 진행될 때 어플리케이션의 상태를 지속적으로 변하지만 정상 실행으로 돌아오지 못하게 하는 방향으로 상태가 변경됨
** 예를 들면, 두 사람이 복도를 지나갈 때 서로를 피하기 위해 왼쪽, 오른쪽으로 움직이지만 계속 서로의 길을 막게 되는 상황
* 교착 상태를 복하도록 설계된 알고리즘에서 라이브 락이 발생하는 경우가 많음

=== 코틀린에서의 동시성

* 코틀린은 동시성에 대해 현대적이고 신선한 접근 방식을 취함. 코틀린을 사용하면 넌 블로킹이며, 가독성 있게 활용될 뿐만 아니라 유연한 동시성 코드를 작성할 수 있음

==== 넌 블로킹

* 스레드는 무겁고 생성하는데 비용이 많이 들며 제한된 수의 스레드만 생성할 수 있음
** 스레드가 블로킹되면 어떻게 보면 자원이 낭비되는 셈
* 코틀린에서는 중단 가능한 연산^Suspendable{sp}Computations^이라는 기능을 제공함
** 스레드의 실행을 블로킹하지 않으면서 실행을 잠시 중단하는 것
* 코틀린은 채널^channels^, 액터^actors^, 상호 배제^mutual{sp}exclustions^와 같은 훌륭한 기본형도 제공해 스레드를 블록하지 않고 동시성 코드를 효과적으로 통신하고 동기화하는 메커니즘 제공

==== 명시적인 선언

[TIP]
====
관례상 기본적으로 동시에 실행될 함수는 async로 시작하거나 Async로 끝나도록 이름을 짓도록 함
====

[NOTE]
====
비동기 함수를 작성하는 대신 suspend 함수를 작성해 async 또는 lanuch 블럭 안에서 호출하는 것이 좋다.
suspend 함수를 갖게 되면 함수의 호출자에게 더 많은 유연성을 제공하기 때문이다.
가령 호출자가 언제 동시적으로 실행할 것인지를 결정할 수 있다.
====

* 동시성은 싶은 고민과 설계가 필요해, 연산이 동시에 실행되야 하는 시점을 명시적으로 만드는 것이 중요함
* 코틀린의 동시성 코드는 순차적 코드만큼 읽기 쉬움 → **가독성**
+
[source, kotlin]
----
suspend fun getProfile(id: Int) {
    val basicUserInfo = getUserInfoAsync(id)
    val contactInfo = getContactInfoAsync(id)

    createProfile(basicUserInfo.await(), contactInfo.await())
}
----
* 코틀린은 동시성 코드를 쉽게 구현할 수 있는 **고급 함수와 기본형** 제공
** `newSingleThreadContext()`: 스레드 이름을 파라미터로 하는 스레드 생성 함수
** `newFixedThreadPoolContext()`: 크기와 이름을 파라미터로 하는 스레드 풀 생성 함수
** `CommonPool`: CPU 바운드 작업에 최적인 스레드 풀
** 코루틴을 다른 스레드로 이동시키는 역할은 런타임이 담당
** 채널, 뮤텍스 및 스레드 한정과 같은 코루틴의 통신과 동기화를 위해 필요한 많은 기본형과 기술이 제공됨
* 코틀린은 간단하면서도 **유연**하게 동시성을 사용하게 해주는 기본형 제공
** **채널^Channels^**: 코루틴 간에 데이터를 안전하게 보내고 받는 데 사용할 수 있는 파이프
** **작업자 풀^Worker{sp}pools^**: 많은 스레드에서 연산 집합의 처리를 나눌 수 있는 코루틴의 풀
** **액터^Actors^**: 채널과 코루틴을 사용하는 상태를 감싼 래퍼. 여러 스레드에서 상태를 안전하게 수정하는 메커니즘 제공
** **뮤텍스^Mutexes^**: 크리티컬 존 영역을 정의해 한번에 하나의 스레드만 실행할 수 있도록 하는 동기화 메커니즘
** **스레드 한정^Thread{sp}confinement^**: 코루틴의 실행을 제한해서 지정된 스레드에서만 실행하도록 하는 기능
** **생성자(반복자 및 시퀀스)**: 필요에 따라 정보를 생성할 수 있고 새로운 정보가 필요하지 않을 때 일시 중단될 수 있는 데이터 소스

=== 코틀린 동시성 관련 개념과 용어

==== 일시 중단 연산^Suspending{sp}computations^
TODO

==== 일시 중단 함수

==== 람다 일시 중단

==== 코루틴 디스패처

==== 코루틴 빌더

== Coroutine

=== 사전 지식

==== 서브루틴^subroutine^

* 여러 명령어를 모아 이름을 부여해서 반복 호출을 할 수 있게 정의한 프로그램 구성 요소(a.k.a. 함수).
* 객체지향 언어에서는 메서드도 서브루틴이라 할 수 있음.
* 서브루틴에 진입하는 방법은 오직 한 가지 뿐.
** 해당 함수를 호출하면 서브루틴의 맨 처음부터 실행 시작.
** 시작될 때 마다 활성 레코드^activation{sp}record^가 스택에 할당되면서 서브루틴 내부의 로컬 변수 등이 초기화 됨.
* 서브루틴 안에서 여러 번 _return_ 을 사용할 수 있음.
** 서브루틴이 실행을 중단하고 제어를 호출한쪽^caller^에게 돌려주는 지점은 여럴 있을 수 있음.
** 다만 서브루틴에서 반환되고 나면 활성 레코드가 스택에서 사라지기 때문에 실행 중이던 모든 상태를 잃어버림.
*** 서브루틴을 여러 번 반복 실행해도 항상 같은 결과를 얻게 됨(side-effect가 있지 않는 한)

==== 멀티태스킹^multitasking^

* 여러 작업을 동시에 수행하는 것처럼 보이거나, 실제로 동시에 수행하는 것.

==== 비선점형^non-preemptive^

* 멀티태스킹의 각 작업을 실행하는 참여자들의 실행을 운영체제가 강제로 일시 중단시키고 다른 참여자를 실행하게 만들 수 없다는 뜻.
* 각 참여자들이 서로 자발적으로 협력해야만 비선점형 멀티태스킹이 제대로 작동할 수 있음.

=== Coroutine?

[CAUTION]
====
코루틴^Coroutine^은 Kotlin만의 기능은 아니지만, Kotlin을 사용하면서 처음 접하게 되어서 `/kotlin` 에 추가하였다.
====

[quote, 위키백과, 코루틴]
____
코루틴(coroutine)은 루틴의 일종으로서, 협동 루틴이라 할 수 있다(코루틴의 "Co"는 with 또는 togather를 뜻한다). 상호 연계 프로그램을 일컫는다고도
표현가능하다. 루틴과 서브 루틴은 서로 비대칭적인 관계이지만, 코루틴들은 완전히 대칭적인, 즉 서로가 서로를 호출하는 관계이다. 코루틴들에서는 무엇이 무엇의 
서브루틴인지를 구분하는 것이 불가능하다. 코루틴 A와 B가 있다고 할 때, A를 프로그래밍 할 때는 B를 A의 서브루틴으로 생각한다. 그러나 B를 프로그래밍할 때는 
A가 B의 서브루틴이라고 생각한다. 어떠한 코루틴이 발동될 때 마다 해당 코루틴은 이전에 자신의 실행이 마지막으로 중단되었던 지점 다음의 장소에서 실행을 재개한다.
____

[quote, Kotlin in Action]
____
코루틴은 컴퓨터 프로그램 구성 요소 중 하나로 비선점형 멀티태스킹(non-preemptive multitasking)을 수행하는 일반화한 서브루틴(subroutine)이다.
코루틴은 실행을 일시 중단(suspend)하고 재개(resume)할 수 있는 여러 진입 지점(entry point)을 허용한다.
____

.코루틴^coroutine^은
* 코틀린^kotlin^과 이름이 비슷해서 코틀린 기능이라고 생각할 수 있지만, 여러 언어에서 지원하는 개념.
* concurrency design pattern.
* 코틀린 팀은 코루틴을 `경량 스레드: Light-weighted thread` 로 정의.
** 한 thread에서 다수의 coroutine을 수행할 수 있음과 Context Switching이 필요없기 때문에 이렇게 부름

.코루틴을 사용하면
* Thread 보다 리소스를 더 효율적으로 사용하면서 더 쉽게 작동.
* Thread는 아니지만 비동기적인^asynchronous^ 프로그래밍이 가능하게 만들어줌.
* Thread는 '중단^block^'되지만, Coroutine은 '보류^suspend^' 됨.
* Thread보다 더 좋은 성능을 제공.
* Thread는 중단될 때 중단이 풀릴 때까지 아무 일도 할 수 없음.
* 코루틴은 Thread에 의해 실행되며, 코루틴을 실행하는 스레드를 중단시키지 않음.
** 대신에 보류된 함수를 실행하는 Thread는 다른 Coroutine을 실행하는 데 사용될 수 있음.
** 내부적으로 실행이 보류되는 함수를 `suspend` 키워드로 나타냄.

[plantuml]
----
@startuml
[Component] --> Interface1
[Component] -> Interface2
@enduml
----

=== Thread vs Coroutine

=== Kotlin의 Coroutine

* Kotlin 1.1부터 코루틴 API 제공
* Kotlin 1.3부터 표준 라이러리에 정식 포함
* 코루틴을 사용하려면 https://github.com/Kotlin/kotlinx.coroutines[코루틴 확장 라이브러리]가 필요하다.
+
https://github.com/Kotlin/kotlinx.coroutines
* 코루틴 라이브러리에서 제공하는 `async` 함수를 사용하면 코루팀을 생성할 수 있다.

==== Suspending functions


---

[source, kt]
.async 생성하기
----
import kotlinx.coroutines.Deferred
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.async

fun fetchCharacterData(): Deferred<CharacterGenerator.CharacterData> { // <1>
  return GlobalScope.async { // <2>
    val apiData = URL(API_URL).readText()
    CharacterGenerator.fromApiData(apiData)
  }
}
----
<1> `Deferred` 는 우리가 요청할 때까지 데이터를 반환하지 않는다.
<2>  `async` 는 하나의 인자로 람다를 받으며, 람다에 백그라운드에서 처리할 작업을 지정한다.


[source, kt]
.await로 결과 기다리기
----
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch

class AppService {
  fun onCreate() {
    GlobalScope.launch(Dispatchers.Main) { // <1> <2>
      characterData = fetchCharacterData().await() <4>
      displayData() // <3>
    }
  }
}
----
<1> `launch` 함수는 코루팀을 생성하며, `launch` 함수는 블록안에 지정한 람다(코루틴 코드)를 시작시킨다.
<1> `launch` 함수의 파라미터에는 해당 작업이 실행되는 스레드를 나타낸다. `Dispatcher.Main` 은 안드로이드의 UI 스레드이다.
<3> 이 코드를 안드로이드로 예를 들었을 때, `displayData()` 함수는 UI를 변경시키는 작업이므로, UI 스레드를 지정시켰다.
<4> 코루틴 컨텍스트의 기본 인자는 `CommonPool` 이다. 이것은 코루틴이 실행될 때 사용될 수 있는 백그라운드 스레드 풀이다. +
    따라서 `await` 를 호출할 때 해당 작업은 CommonPool의 스레드 중 하나를 사용한다.

=== launch vs async/await

* `async`, `launch` 함수를 coroutine builder function 이라고 한다.
** 이 함수들은 특정 방법으로 작업을 수행하도록 코루틴을 설정한다.
* `launch` 는 우리가 지정한 작업을 올바르게 수행하는 코루틴을 빌드한다.
* `async` 는 지연된(아직 완료되지 않은) 작업을 나타내는 `Deferred` 를 반환하는 코루팀을 빌드한다.
** 즉, 해당 작업이 바로 시작되어 끝나는 것이 아니다.
* `Deferred` 타입은 `await` 함수를 제공한다.
** `await` 함수는 우리가 원하는 작업 수행 시점에 호출한다.
** `await` 함수는 지연된 작업이 완료될 때까지 다음에 할 작업을 보류한다.
* `Deferred` 는 Java의 `Future` 와 유사한 방법으로 동작한다.

=== yield

=== reactive vs coroutine

=== Fiber

=== References

* https://github.com/hikaMaeng/kotlinCoroutineKR[코루틴 번역]
* https://wooooooak.github.io/kotlin/2019/08/25/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%BD%94%EB%A3%A8%ED%8B%B4-%EA%B0%9C%EB%85%90-%EC%9D%B5%ED%9E%88%EA%B8%B0/[코틀린 코루틴(coroutine) 개념 익히기]
* https://stylishc.tistory.com/128


=== _WebClient_ with Coroutines

https://www.baeldung.com/spring-boot-kotlin-coroutines

suspending extension 함수인 `awaitBody()` 를 활용할 수 있다.

[source, kotlin]
----
val htmlResponse = webClient.get()
    .uri("https://www.baeldung.com/")
    .retrieve()
    .awaitBody<String>()
----

`retrieve()` 함수는 API 요청의 응답 코드가 2xx일 경우에만 반환하고, 나머지는 예외를 던진다. 다양한 응답 코드에 대한
핸들링이 필요하다면 `awaitExchange()` 확장 함수를 활용할 수 있다.

[source, kotlin]
----
val response: ResponseEntity<String> = webClient.get()
    .uri("https://www.baeldung.com/")
    .awaitExchange()
    .awaitEntity()
----

위와 같은 코드에서는 API 응답이 `ResponseEntity` 로 반환되므로, 상태 코드에 따른 처리가 가능해진다.

[source, kotlin]
----
@GetMapping("/payments/{id}/")
suspend fun fundPayment(@PathVariable id: String): PaymentView {
    val 

    return PaymentView()
}
----
