= Coroutine

* Kotlin 1.3부터 표준 라이러리에 정식 포함
* 코루틴을 사용하면 비동기적으로 작업을 실행시킬 수 있다.
* 코루틴은 concurrency design pattern 이다.
* 이름이 비슷해서 코틀린 기능이라고 생각할 수 있지만 여러 언어에서 지원하는 개념이다.
* 코루틴을 사용하려면 https://github.com/Kotlin/kotlinx.coroutines[코루틴 확장 라이브러리]가 필요하다.
* 코루틴 라이브러리에서 제공하는 `async` 함수를 사용하면 코루팀을 생성할 수 있다.
* Thread는 '중단(block)'되지만, Coroutine은 '보류(suspend)'된다.
** Coroutine은 Thread보다 더 좋은 성능을 제공한다.
** Thread는 중단될 때 중단이 풀릴 때까지 아무 일도 할 수 없다.
** 코루틴은 Thread에 의해 실행되며, 코루틴을 실행하는 스레드를 중단시키지 않는다.
** 대신에 보류된 함수를 실행하는 Thread는 다른 Coroutine을 실행하는 데 사용될 수 있다.
** 내부적으로 실행이 보류되는 함수를 `suspend` 키워드로 나타낸다.

[source, kt]
.async 생성하기
----
import kotlinx.coroutines.Deferred
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.async

fun fetchCharacterData(): Deferred<CharacterGenerator.CharacterData> { // <1>
  return GlobalScope.async { // <2>
    val apiData = URL(API_URL).readText()
    CharacterGenerator.fromApiData(apiData)
  }
}
----
<1> `Deferred` 는 우리가 요청할 때까지 데이터를 반환하지 않는다.
<2>  `async` 는 하나의 인자로 람다를 받으며, 람다에 백그라운드에서 처리할 작업을 지정한다.


[source, kt]
.await로 결과 기다리기
----
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch

class AppService {
  fun onCreate() {
    GlobalScope.launch(Dispatchers.Main) { // <1> <2>
      characterData = fetchCharacterData().await() <4>
      displayData() // <3>
    }
  }
}
----
<1> `launch` 함수는 코루팀을 생성하며, `launch` 함수는 블록안에 지정한 람다(코루틴 코드)를 시작시킨다.
<1> `launch` 함수의 파라미터에는 해당 작업이 실행되는 스레드를 나타낸다. `Dispatcher.Main` 은 안드로이드의 UI 스레드이다.
<3> 이 코드를 안드로이드로 예를 들었을 때, `displayData()` 함수는 UI를 변경시키는 작업이므로, UI 스레드를 지정시켰다.
<4> 코루틴 컨텍스트의 기본 인자는 `CommonPool` 이다. 이것은 코루틴이 실행될 때 사용될 수 있는 백그라운드 스레드 풀이다. +
    따라서 `await` 를 호출할 때 해당 작업은 CommonPool의 스레드 중 하나를 사용한다.

=== launch vs async/await

* `async`, `launch` 함수를 coroutine builder function 이라고 한다.
** 이 함수들은 특정 방법으로 작업을 수행하도록 코루틴을 설정한다.
* `launch` 는 우리가 지정한 작업을 올바르게 수행하는 코루틴을 빌드한다.
* `async` 는 지연된(아직 완료되지 않은) 작업을 나타내는 `Deferred` 를 반환하는 코루팀을 빌드한다.
** 즉, 해당 작업이 바로 시작되어 끝나는 것이 아니다.
* `Deferred` 타입은 `await` 함수를 제공한다.
** `await` 함수는 우리가 원하는 작업 수행 시점에 호출한다.
** `await` 함수는 지연된 작업이 완료될 때까지 다음에 할 작업을 보류한다.
* `Deferred` 는 Java의 `Future` 와 유사한 방법으로 동작한다.

== Tip

* https://plugins.jetbrains.com/plugin/10081-edutools[kotlin 실습으로 배우기]
* https://github.com/Kotlin/KEEP[KEEP - Kotlin Evolution and Enhancement Process]
** https://github.com/hikaMaeng/kotlinCoroutineKR[코루틴 번역]