= Effective Kotlin
:toc: left
:toclevels: 3
:sectnums:
:sectnumlevels: 3
// :appendix-caption: 부록
// :idprefix: item_

[discrete]
== 들어가기 앞서

* 코틀린의 핵심 철학은 '실용주의(pragmatism)'
* 실용주의는 다음과 같은 비지니스 요구 사항을 충족한다는 것을 의미
** 생선성(productivity)
** 확장성(scalability)
** 유지보수성(maintainability)
** 신뢰성(reliability)
** 효율성(efficiency)
* 이 책의 목표
+
코틀린을 활용해서 더 안전하고, 더 가독성이 좋고, 더 확장성이 있으며, 더 효율적인 코드를 작성하는 방법 설명

// [dedication%untitled]
[discrete]
== 좋은 코드

[#safety]
[discrete]
=== 안정성

[#item1]
==== 가변성을 제한하라


* 코틀린의 프로퍼티는 상태(state)를 가질 수 있음.
+
read-write property(`var`) 혹은 mutable object
* 상태를 가지는 것
** 프로그램 이해하기 어렵고 디버그 어려워짐
** 코드 실행을 추론하기 어려워짐
** 멀티스레드일 때 적절한 동기화 필요
** 테스트 어려워짐
** 변경을 알려야함
+
(정렬된 리스트일 경우 엘리먼트 변경시 매번 재정렬 필요)
* 가변성은 생각보다 단점이 많아 이를 제한하는 언어도 있음 → 순수 함수형 언어(Haskell, ...)
* 일반적으로 `var` 보다 `val` 을 많이 사용함
* 코틀린은 가변성을 제한할 수 있게 설계되어 있음

===== 읽기 전용 프로퍼티(`val`)

* `val` 로 선언된 프로퍼티는 마치 값(value)처럼 동작
* **읽기 전용 프로퍼티가 완전히 변경 불가능한 것은 아니라는 것을 주의**
+
`val` 은 읽기 전용 프로퍼티지만, 변경할 수 없음(불변, immutable)을 의미하는 것이 아니라는 것을 기억해야 함
* 읽기 전용 프로퍼티가 mutable 객체를 담고 있다면, 내부적으로 변경 가능
+
'프로퍼티를 읽을 수만 있다는 것(읽기 전용) vs. 값이 변할 수 없는 것(가변성)' 구분할 줄 알아야 함
* 읽기 전용 프로퍼티는 다른 프로퍼티를 활용하는 사용자 정의 게터로도 정의 가능
+
[source, kotlin]
----
var id = "1"
var name = "jun"
val key
    get() = "$id:$name" <1>

fun main() {
    println(key) // 1:jun
    id = 2
    println(key) // 2:jun <2>
}
----
<1> 사용자 정의 게터
<2> `val` 임에도 불구하고 값이 변경됨

* 코틀린의 프로퍼티는 기본적으로 캡슐화 되어 있고, 사용자 정의 접근자(getter, setter) 가질 수 있음 = 유연함 제공
+
(아이템 16 참고)
* `val` 을 `var` 로 오버라이드 가능
+
[source, kotlin]
----
interface Element {
    val active: Boolean
}

class ActualElement: Element {
    override var active: Boolean = false
}

fun main() {
    with(ActualElement()) {
        println(active) // false
        active = true
        println(active) // true
    }
}
----

===== 가변 컬렉션과 읽기 전용 컬렉션 구분

* 읽기 전용 인터페이스: `Iterable`, `Collection`, `Set`, `List`
* 읽고 쓸 수 있는 인터페이스: `MutableIterable`, `MutableCollection`, `MutableSet`, `MutableList`
* 읽기 전용 컬렉션을 mutable 컬렉션으로 다운캐스팅하면 안됨
+
(해당 인터페이스의 계약을 위반하고, 추상화를 무시하는 행위. 안전하지 못하고, 예측하지 못한 결과를 초래함)
+
[source, kotlin]
----
val list = listOf(1, 2, 3)

// 하지 말아야 할 행위. 다운캐스팅
if (list is MutableList) {
    list.add(4)
}
----

* 복제(copy)를 통해 새로운 mutable 컬렉션을 만드는 `list.toMutableList` 를 활용해야 함

===== 데이터 클래스의 `copy`

* `data` 한정자는 `copy` 라는 이름의 메서드를 만들어 줌
* `String` 이나 `Int` 처음 내부적인 상태를 변경하지 않는 immutable 객체를 많이 사용하는 데에는 이유가 있음
** 변경되지 않으므로(상태가 유지되므로) 코드 이해하기 쉬움
** 공유시 충돌 X, 안전하게 병렬 처리
** 쉽게 캐싱할 수 있음
** 방어적 복사본(defensive copy)을 만들 필요가 없음. 또한 깊은 복사하지 않아도 됨
** 실행을 쉽게 예측할 수 있음
** 맵, 셋의 키로도 사용 가능

==== 변수의 스코프를 최소화하라


_The Pragmatic Programmer_ <<pp>> should be required reading for all developers.
To learn all about design patterns, refer to the book by the "`Gang of Four`" <<gof>>.

[discrete]
== 코드 설계

[discrete]
=== 재사용성

[#item19]
==== knowledge를 반복하여 사용하지 말라

[appendix]
== test

https://play.kotlinlang.org/

[glossary]
== Glossary

[glossary]
mud:: wet, cold dirt
rain::
	water falling from the sky

[bibliography]
== References

* [[[pp]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
From Journeyman to Master. Addison-Wesley. 1999.
* [[[gof,gang]]] Erich Gamma, Richard Helm, Ralph Johnson & John Vlissides.
Design Patterns: Elements of Reusable Object-Oriented Software. Addison-Wesley. 1994.